import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["der Job", "job", "noun"],
  ["die E-Mail", "e-mail", "noun"],
  ["stellen", "to place / put", "verb"],
  ["gegenseitig", "each other", "adjective"],
  ["das Hallo", "hello", "noun"],
  ["beide", "both", "other"],
  ["herzlich", "cordial / heartfelt", "adjective"],
  ["der Glückwunsch", "congratulation", "noun"],
  ["neu", "new", "adjective"],
  ["das Büro", "office", "noun"],
  ["mutig", "courageous", "adjective"],
  ["die Power", "power", "noun"],
  ["übrigens", "by the way", "adverb"],
  ["die Neuigkeit", "news", "noun"],
  ["der Monat", "month", "noun"],
  ["beruflich", "professional", "adjective"],
  ["gründen", "to found / establish", "verb"],
  ["ziehen", "to move / pull", "verb"],
  ["mittelgroß", "medium-sized", "adjective"],
  ["die Firma", "company", "noun"],
  ["bekommen", "to get / receive", "verb"],
  ["der Mitarbeiter", "employee / staff member", "noun"],
  ["die Mitarbeiterin", "female employee", "noun"],
  ["das Badmöbel", "bathroom furniture", "noun"],
  ["der Mensch", "person / human", "noun"],
  ["die Behinderung", "disability", "noun"],
  ["der Einkauf", "purchase / shopping", "noun"],
  ["verantwortlich", "responsible", "adjective"],
  ["sehr", "very", "adverb"],
  ["ständig", "constant / constantly", "other"],
  ["arbeiten", "to work", "verb"],
  ["der Kollege", "male colleague", "noun"],
  ["die Kollegin", "female colleague", "noun"],
  ["der Kontakt", "contact", "noun"],
  ["die Fortbildung", "training / further education", "noun"],
  ["hoch", "high", "adjective"],
  ["die Mietpreis", "rental price", "noun"],
  ["die Wohnung", "apartment / housing", "noun"],
  ["die Altstadt", "old town", "noun"],
  ["finden", "to find", "verb"],
  ["das Glück", "happiness / luck", "noun"],
  ["die Einweihungsparty", "housewarming party", "noun"],
  ["viel", "many / much", "other"],
  ["der Dank", "thanks", "noun"],
  ["die Einladung", "invitation", "noun"],
  ["die Liebe", "love", "noun"],
  ["der Gruß", "greeting", "noun"],
  ["das Warum", "the why", "noun"],
  ["umziehen", "to move house", "verb"],
  ["der Begriff", "term / concept", "noun"],
  ["zweit", "second", "adjective"],
  ["der Ort", "place", "noun"],
  ["die Art", "species / kind / type", "noun"],
  ["weise", "wise", "adjective"],
  ["der Grund", "reason", "noun"],
  ["der Widerspruch", "contradiction", "noun"],
  ["der Fokus", "focus", "noun"],
  ["die Angabe", "information / detail", "noun"],
  ["die Wann-warum-wie-wo-Regel", "when-why-how-where rule", "noun"],
  ["zen", "Zen", "noun"],
  ["wohin", "where to", "adverb"],
  ["die Ich-habe", "the I have", "noun"],
  ["erst", "first", "other"],
  ["der Satz", "sentence / rate", "noun"],
  ["das Kärtchen", "small card", "noun"],
  ["spielen", "to play", "verb"],
  ["der Pen", "pen", "noun"],
  ["probieren", "to try", "verb"],
  ["die Position", "position", "noun"],
  ["stehen", "to stand", "verb"],
  ["der März", "March", "noun"],
  ["der Ausdruck", "expression", "noun"],
  ["die Tabelle", "table", "noun"],
  ["der Monat", "month", "noun"],
  ["spät", "late", "adjective"],
  ["der Nachmittag", "afternoon", "noun"],
  ["draußen", "outside", "adverb"],
  ["wegen", "because of / due to", "other"],
  ["die Ausbildung", "training / education", "noun"],
  ["das Problem", "problem", "noun"],
  ["das Zentrum", "centre", "noun"],
  ["gut", "good", "adjective"],
  ["die Verkehrsanbindung", "transport connection", "noun"],
  ["das Land", "country", "noun"],
  ["die Entspannung", "relaxation", "noun"],
  ["gestern", "yesterday", "adverb"],
  ["der Vorort", "suburb", "noun"],
  ["machen", "to make / do", "verb"],
  ["das Kettenspiel", "chain game", "noun"],
  ["bilden", "to form", "verb"],
  ["ausdrücken", "to express", "verb"],
  ["umziehen", "to move", "verb"],
  ["viel", "much / many", "other"],
  ["kommen", "to come", "verb"],
  ["die Pflegerin", "nurse / caretaker", "noun"],
  ["zuerst", "first", "adverb"],
  ["der Umzug", "move / relocation", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const ADILS_JOB_SET_ID = "58f9f2b4-c4ca-4d67-ba44-941d194d2e16";
export const ADILS_JOB_SET_NAME = "Kapitel 1 - Adils neuer Job";

export function getAdilsJobSet(): StudySet {
  return {
    id: ADILS_JOB_SET_ID,
    name: ADILS_JOB_SET_NAME,
    createdAt: 0,
    sourceImageCount: 1,
    words: RAW_WORDS.map((word, index) => ({ id: `${ADILS_JOB_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
