import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["der Leiter", "ladder / manager", "noun"],
  ["die Kaffeemaschine", "coffee machine", "noun"],
  ["die Werkbank", "workbench", "noun"],
  ["der Hocker", "stool", "noun"],
  ["das Büroregal", "office shelf", "noun"],
  ["die Klimaanlage", "air conditioning", "noun"],
  ["der Bildschirm", "screen / monitor", "noun"],
  ["das Werkzeug", "tool", "noun"],
  ["der Arbeitstisch", "work table", "noun"],
  ["der Kasten", "box", "noun"],
  ["der Putzeimer", "cleaning bucket", "noun"],
  ["der Arbeitsraum", "workspace", "noun"],
  ["die Tätigkeit", "activity", "noun"],
  ["das Gerät", "device / equipment", "noun"],
  ["sammeln", "to collect", "verb"],
  ["das Gespräch", "conversation", "noun"],
  ["passen", "to fit", "verb"],
  ["die Kaffeeküche", "coffee kitchen / kitchenette", "noun"],
  ["die Einweihungsparty", "housewarming party", "noun"],
  ["der Büroraum", "office space", "noun"],
  ["der Umzugsablauf", "moving process", "noun"],
  ["beschreiben", "to describe", "verb"],
  ["das Angebot", "offer", "noun"],
  ["verhandeln", "to negotiate", "verb"],
  ["das Beratungsgespräch", "consultation", "noun"],
  ["durchführen", "to carry out / conduct", "verb"],
  ["der Firmenumzug", "company relocation", "noun"],
  ["organisieren", "to organize", "verb"],
  ["der Mangel", "deficiency / shortcoming", "noun"],
  ["reklamieren", "to complain about / make a complaint", "verb"],
  ["die Absprache", "agreement / arrangement", "noun"],
  ["die Umzugsfirma", "moving company", "noun"],
  ["die Mängelmeldung", "defect report", "noun"],
  ["gründen", "to found / establish", "verb"],
  ["aufmerksam", "attentive", "adjective"],
  ["die Mieterhöhung", "rent increase", "noun"],
  ["die Suche", "search", "noun"],
  ["die Renovierung", "renovation", "noun"],
  ["die Zusage", "confirmation / acceptance", "noun"],
  ["die Krise", "crisis", "noun"],
  ["der Vermieter", "landlord", "noun"],
  ["die Miete", "rent", "noun"],
  ["erhöhen", "to increase / raise", "verb"],
  ["leisten", "to provide / achieve", "verb"],
  ["die Auftragslage", "order situation / order volume", "noun"],
  ["achten", "to pay attention", "verb"],
  ["derselbe / dieselbe / dasselbe", "the same", "other"],
  ["der laufende", "ongoing / current", "adjective"],
  ["eher", "rather", "adverb"],
  ["die Altbauwohnung", "apartment in an old building", "noun"],
  ["die Einbauküche", "fitted kitchen", "noun"],
  ["der Stock", "floor / story", "noun"],
  ["der Fahrstuhl", "elevator", "noun"],
  ["die Kundschaft", "customers / clientele", "noun"],
  ["das Gebäude", "building", "noun"],
  ["furchtbar", "terrible", "adjective"],
  ["der Zustand", "condition", "noun"],
  ["das Werkstattgebäude", "workshop building", "noun"],
  ["teilweise", "partly / partially", "adverb"],
  ["die Werkstatt", "workshop", "noun"],
  ["vormerken", "to put on a list / note for later", "verb"],
  ["die Unterlage", "document", "noun"],
  ["die Hausverwaltung", "property management company", "noun"],
  ["der Daumen", "thumb", "noun"],
  ["das Telefonat", "telephone call", "noun"],
  ["ehemalig", "former", "adjective"],
  ["der Anfang", "beginning / start", "noun"],
  ["renovieren", "to renovate", "verb"],
  ["der Auszug", "move-out", "noun"],
  ["der Boden", "floor", "noun"],
  ["der Handwerker", "tradesperson / craftsman", "noun"],
  ["abschleifen", "to sand / grind down", "verb"],
  ["die Wand", "wall", "noun"],
  ["der Spezialist", "specialist", "noun"],
  ["sanieren", "to renovate / refurbish", "verb"],
  ["der Internetanschluss", "internet connection", "noun"],
  ["der Server", "server", "noun"],
  ["der Netzwerktechniker", "network technician", "noun"],
  ["erledigen", "to take care of / complete", "verb"],
  ["anschließen", "to connect", "verb"],
  ["der Anschluss", "connection", "noun"],
  ["der Elektriker", "electrician", "noun"],
  ["legen", "to lay / put", "verb"],
  ["der Umzug", "move / relocation", "noun"],
  ["die Spedition", "moving / freight company", "noun"],
  ["die Festplatte", "hard drive", "noun"],
  ["transportieren", "to transport", "verb"],
  ["der Sicherheitsgrund", "safety reason", "noun"],
  ["der Möbelpacker", "furniture mover", "noun"],
  ["der Schrank", "cabinet / cupboard", "noun"],
  ["der Büroraum", "office space", "noun"],
  ["der Auftrag", "order / assignment", "noun"],
  ["der Ausdruck", "expression", "noun"],
  ["vergleichen", "to compare", "verb"],
  ["der Mietvertrag", "rental contract / lease", "noun"],
  ["unterschreiben", "to sign", "verb"],
  ["das Möbelhaus", "furniture store", "noun"],
  ["das Büromöbel", "office furniture", "noun"],
  ["ansehen", "to look at / view", "verb"],
  ["der Nachsendeantrag", "mail forwarding request", "noun"],
  ["der Umzugskarton", "moving box", "noun"],
  ["packen", "to pack", "verb"],
  ["das Internetportal", "internet portal", "noun"],
  ["der Einkommensnachweis", "proof of income", "noun"],
  ["das Maklerbüro", "real estate agency", "noun"],
  ["kontaktieren", "to contact", "verb"],
  ["ummelden", "to re-register", "verb"],
  ["beauftragen", "to commission / hire", "verb"],
  ["die Kaution", "deposit", "noun"],
  ["hinterlegen", "to deposit", "verb"],
  ["der Grundriss", "floor plan", "noun"],
  ["die Vermieterin", "landlady", "noun"],
  ["die Liste", "list", "noun"],
  ["der Mitarbeiter", "employee / staff member", "noun"],
  ["der Handwerker", "tradesperson / craftsman", "noun"],
  ["der Fliesenleger", "tiler", "noun"],
  ["der Schreiner", "carpenter", "noun"],
  ["fliesen", "to tile", "verb"],
  ["der Maler", "painter", "noun"],
  ["der Installateur", "plumber / installer", "noun"],
  ["holen", "to fetch / get", "verb"],
  ["der Dachdecker", "roofer", "noun"],
  ["der Heizungsbauer", "heating technician", "noun"],
  ["der Bodenleger", "flooring installer", "noun"],
  ["der Maurer", "bricklayer / mason", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const ARBEITSRAEUME_SET_ID = "41a3417a-43ac-44e8-96ff-8b863209587f";
export const ARBEITSRAEUME_SET_NAME = "Kapitel 1 - Arbeitsräume";

export function getArbeitsraeumeSet(): StudySet {
  return {
    id: ARBEITSRAEUME_SET_ID,
    name: ARBEITSRAEUME_SET_NAME,
    createdAt: 0,
    sourceImageCount: 3,
    words: RAW_WORDS.map((word, index) => ({ id: `${ARBEITSRAEUME_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
