import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["Hier arbeite ich.", "Here I work.", "phrase"],
  ["Renovierung: Wer macht was?", "Renovation: Who does what?", "phrase"],
  ["Drückt uns die Daumen!", "Keep your fingers crossed for us!", "phrase"],
  ["Man muss schnell sein ...", "You have to be fast...", "phrase"],
  ["Das hat ja super geklappt!", "That worked out super well!", "phrase"],
  ["auf unsere Kosten achten", "to watch our costs", "phrase"],
  ["in der engeren Auswahl", "in the shortlist / running", "phrase"],
  ["auf dem Laufenden", "up to date / informed", "phrase"],
  ["ein Erfolgserlebnis", "a sense of achievement", "phrase"],
  ["von der Stadtmitte", "from the city center", "phrase"],
  ["uns total freuen", "to be totally happy / excited", "phrase"],
  ["mit unserem Team zusammensetzen", "to sit down with our team", "phrase"],
  ["selbst anschließen", "to connect oneself / hook up oneself", "phrase"],
  ["aus Sicherheitsgründen", "for safety reasons", "phrase"],
  ["mit einem Sekt anstoßen", "to toast with sparkling wine", "phrase"],
  ["den Mietvertrag unterschreiben", "to sign the lease", "phrase"],
  ["einen Nachsendeantrag stellen", "to submit a mail forwarding request", "phrase"],
  ["Objekte besichtigen", "to view properties", "phrase"],
  ["vormerken lassen", "to have oneself put on a waiting list", "phrase"],
  ["einen Maklerbüro kontaktieren", "to contact a real estate agency", "phrase"],
  ["eine Kaution hinterlegen", "to deposit a security bond", "phrase"],
  ["den Vermieter kontaktieren", "to contact the landlord", "phrase"],
  ["die Möbel selbst abbauen", "to dismantle the furniture oneself", "phrase"],
  ["die Kartons selbst packen", "to pack the boxes oneself", "phrase"],
  ["bezüglich des Termins flexibel", "flexible regarding the appointment", "phrase"],
  ["beim Preis etwas Spielraum", "some leeway with the price", "phrase"],
  ["Termin entgegenkommen", "to accommodate an appointment", "phrase"],
  ["Wände streichere ich selbst", "I paint the walls myself", "phrase"],
  ["herzlichen Glückwunsch zum neuen Büro!", "congratulations on the new office!", "phrase"],
  ["aus beruflichen Gründen", "for professional reasons", "phrase"],
  ["von einem Monat", "a month ago", "phrase"],
  ["eine Fortbildung bekommen", "to receive further training", "phrase"],
  ["trotz der hohen Mietpreise", "despite the high rental prices", "phrase"],
  ["Glück muss man haben!", "You have to have luck!", "phrase"],
  ["vielen Dank für die Einladung!", "thank you very much for the invitation!", "phrase"],
  ["Wir fühlen uns sehr wohl hier", "We feel very comfortable here", "phrase"],
  ["Das geht dann schnell!", "That will go quickly then!", "phrase"],
  ["Das kann doch nicht wahr sein!", "That can't be true!", "phrase"],
  ["Ich kümmere mich", "I'll take care of it", "phrase"],
  ["Die Zentralheizung funktioniert nicht", "The central heating is not working", "phrase"],
  ["Bescheid sagen", "to let someone know / give notice", "phrase"],
  ["den Hausmeister informieren", "to inform the caretaker", "phrase"],
  ["Sehr geehrter Herr Heuermann", "Dear Mr. Heuermann", "phrase"],
  ["Deshalb bitten wir Sie...", "Therefore we ask you...", "phrase"],
  ["so schnell wie möglich", "as quickly as possible", "phrase"],
  ["den Schaden beheben", "to fix the damage", "phrase"],
  ["Bei Bedarf", "If needed / upon request", "phrase"],
  ["einen anderen Termin vereinbaren", "to arrange a different appointment", "phrase"],
  ["Vor unserem Einzug", "Before our move-in", "phrase"],
  ["Ich beziehe mich auf...", "I am referring to...", "phrase"],
  ["Wie soeben besprochen", "As just discussed", "phrase"],
  ["Vielen Dank im Voraus!", "Many thanks in advance!", "phrase"],
  ["Mit freundlichen Grüßen", "Kind regards", "phrase"],
  ["Hiermit möchte ich Sie bitten...", "Hereby I would like to ask you...", "phrase"],
  ["Wir hatten vereinbart, dass...", "We had agreed that...", "phrase"],
  ["Falls Sie noch Rückfragen haben...", "If you have any further questions...", "phrase"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const AUSDRUECKE_SET_ID = "ausdruecke-kapitel-1";
export const AUSDRUECKE_SET_NAME = "Kapitel 1 - Ausdrücke";

export function getAusdrueckeSet(): StudySet {
  return {
    id: AUSDRUECKE_SET_ID,
    name: AUSDRUECKE_SET_NAME,
    createdAt: 0,
    sourceImageCount: 0,
    words: RAW_WORDS.map((word, index) => ({ id: `${AUSDRUECKE_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
