import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["der Beitrag", "contribution / post", "noun"],
  ["das Gründerforum", "founders' forum", "noun"],
  ["negativ", "negative", "adjective"],
  ["die Erfahrung", "experience", "noun"],
  ["positiv", "positive", "adjective"],
  ["der Tipp", "tip", "noun"],
  ["der Modeladen", "fashion shop / boutique", "noun"],
  ["aufmachen", "to open", "verb"],
  ["der Abschluss", "completion / degree", "noun"],
  ["die Schneiderin", "tailor / seamstress", "noun"],
  ["die Nachfrage", "demand", "noun"],
  ["die Bekannte", "acquaintance", "noun"],
  ["nähen", "to sew", "verb"],
  ["ähnlich", "similar", "adjective"],
  ["selbstständig", "self-employed", "adjective"],
  ["die Idee", "idea", "noun"],
  ["abbringen", "to dissuade / take away", "verb"],
  ["die Einnahme", "income / revenue", "noun"],
  ["unternehmen", "to undertake", "verb"],
  ["das Unternehmen", "enterprise", "noun"],
  ["der Richtige", "the right one", "noun"],
  ["schauen", "to look", "verb"],
  ["das Stichwort", "keyword", "noun"],
  ["der Existenzgründer", "business starter / founder", "noun"],
  ["niemand", "no one", "other"],
  ["der Blumenladen", "flower shop", "noun"],
  ["pleitegehen", "to go bankrupt", "verb"],
  ["der Laden", "shop / store", "noun"],
  ["der Kredit", "credit / loan", "noun"],
  ["aufnehmen", "to take out / record", "verb"],
  ["zurückzahlen", "to pay back", "verb"],
  ["niedergeschlagen", "dejected / downcast", "adjective"],
  ["auf jeden Fall", "in any case", "phrase"],
  ["prüfen", "to check / examine", "verb"],
  ["die Finanzreserve", "financial reserve", "noun"],
  ["die Bank", "bank", "noun"],
  ["das Crowdfunding", "crowdfunding", "noun"],
  ["die Möglichkeit", "possibility", "noun"],
  ["die Ladengemeinschaft", "shop community / shared store", "noun"],
  ["gründen", "to establish / found", "verb"],
  ["die Gewerbefläche", "commercial space / industrial land", "noun"],
  ["billig", "cheap", "adjective"],
  ["der Meister", "master craftsman", "noun"],
  ["der Himmel", "heaven / sky", "noun"],
  ["fallen", "to fall", "verb"],
  ["die Stadt", "city", "noun"],
  ["das Seminar", "seminar", "noun"],
  ["der Workshop", "workshop", "noun"],
  ["einige", "some", "other"],
  ["der Kiosk", "kiosk", "noun"],
  ["vorher", "before / previously", "adverb"],
  ["teilnehmen", "to participate", "verb"],
  ["wirtschaftlich", "economic", "adjective"],
  ["rechtlich", "legal", "adjective"],
  ["die Lage", "location / situation", "noun"],
  ["das Geschäft", "business", "noun"],
  ["die Stelle", "spot / agency", "noun"],
  ["der Eintrag", "entry", "noun"],
  ["das Negationswort", "negation word", "noun"],
  ["finden", "to find", "verb"],
  ["markieren", "to mark", "verb"],
  ["ergänzen", "to add / complete", "verb"],
  ["früher", "earlier / previous", "adverb"],
  ["der Erfolg", "success", "noun"],
  ["unzufrieden", "dissatisfied", "adjective"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const BEITRAEGE_SET_ID = "7a8d3b86-5336-4272-8d05-66f8ba48c7f4";
export const BEITRAEGE_SET_NAME = "Kapitel 2 - Beiträge";

export function getBeitraegeSet(): StudySet {
  return {
    id: BEITRAEGE_SET_ID,
    name: BEITRAEGE_SET_NAME,
    createdAt: 0,
    sourceImageCount: 0,
    words: RAW_WORDS.map((word, index) => ({
      id: `${BEITRAEGE_SET_ID}-${index}`,
      ...word,
    })),
    masteredWordIds: [],
  };
}