import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["der Alltag", "daily life", "noun"],
  ["der Späti", "late-night kiosk", "noun"],
  ["der Dienstplan", "work schedule", "noun"],
  ["erstellen", "to create", "verb"],
  ["besprechen", "to discuss", "verb"],
  ["gemeinsam", "together / common", "adjective"],
  ["die Arbeitszeit", "working hours", "noun"],
  ["aushandeln", "to negotiate", "verb"],
  ["übernehmen", "to take over", "verb"],
  ["der Chef", "boss / chief", "noun"],
  ["die Chefin", "female boss", "noun"],
  ["genannt", "named / mentioned", "adjective"],
  ["überlegen", "to consider / think over", "verb"],
  ["duzen", "to use the informal du", "verb"],
  ["siezen", "to use the formal Sie", "verb"],
  ["der Laut", "sound", "noun"],
  ["nächster", "next", "adjective"],
  ["der Grund", "reason", "noun"],
  ["das Schreiben", "letter / writing", "noun"],
  ["die Entschuldigung", "excuse / apology", "noun"],
  ["einhalten", "to comply with / keep", "verb"],
  ["die Lösungsmöglichkeit", "possible solution", "noun"],
  ["der Arbeitsauftrag", "work order / assignment", "noun"],
  ["die Liebe", "love", "noun"],
  ["die Wichtigste", "the main one", "noun"],
  ["die Getränkelieferung", "beverage delivery", "noun"],
  ["anrufen", "to call", "verb"],
  ["das Getränk", "beverage", "noun"],
  ["die Zeitschriftenremittende", "returned magazine", "noun"],
  ["vorbereiten", "to prepare", "verb"],
  ["der Karton", "box / carton", "noun"],
  ["die Firma", "company", "noun"],
  ["erreichbar", "accessible / reachable", "adjective"],
  ["der Gruß", "greetings", "noun"],
  ["das Gespräch", "conversation / interview", "noun"],
  ["ergänzen", "to add / complete", "verb"],
  ["die Notiz", "note", "noun"],
  ["bestellen", "to order", "verb"],
  ["die Telefonnummer", "telephone number", "noun"],
  ["der Kontext", "context", "noun"],
  ["nehmen", "to take", "verb"],
  ["der Auftrag", "order / contract", "noun"],
  ["entgegennehmen", "to receive / accept", "verb"],
  ["formulieren", "to formulate", "verb"],
  ["die Zeichnung", "drawing", "noun"],
  ["abnehmen", "to answer / decrease", "verb"],
  ["abnehmen", "to answer / decrease", "verb"],
  ["erteilen", "to issue / grant", "verb"],
  ["verwenden", "to use", "verb"],
  ["das Redemittel", "phrase / expression", "noun"],
  ["das Verständnis", "understanding", "noun"],
  ["sichern", "to secure", "verb"],
  ["rufen", "to call / shout", "verb"],
  ["natürlich", "of course", "adverb"],
  ["die Ordnung", "order", "noun"],
  ["selbstverständlich", "of course / natural", "adjective"],
  ["verhandeln", "to negotiate", "verb"],
  ["nachfragen", "to inquire / follow up", "verb"],
  ["erledigen", "to do / finish", "verb"],
  ["fertig", "finished", "adjective"],
  ["zuständig", "responsible", "adjective"],
  ["wählen", "to choose / select", "verb"],
  ["stellen", "to put / place", "verb"],
  ["die Gründungsidee", "founding idea", "noun"],
  ["erarbeiten", "to work out / develop", "verb"],
  ["die Geschäftsidee", "business idea", "noun"],
  ["die Information", "information", "noun"],
  ["der Erfinderladen", "inventor's shop", "noun"],
  ["das Ding", "thing", "noun"],
  ["das Schloss", "castle / lock", "noun"],
  ["verantwortlich", "responsible", "adjective"],
  ["der Mitbewohner", "roommate", "noun"],
  ["wegnaschen", "to snack away / nibble away", "verb"],
  ["die Dose", "can / tin", "noun"],
  ["frisch", "fresh", "adjective"],
  ["die Seeluft", "sea air", "noun"],
  ["die Erinnerung", "reminder / memory", "noun"],
  ["das Meer", "sea", "noun"],
  ["präsentieren", "to present", "verb"],
  ["der Kurs", "course", "noun"],
  ["das Café", "café", "noun"],
  ["die Kinderbetreuung", "childcare", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const DIENSTPLAN_SET_ID = "07744c50-6263-4f76-a886-b85628423d32";
export const DIENSTPLAN_SET_NAME = "Kapitel 2 - Dienstplan";

export function getDienstplanSet(): StudySet {
  return {
    id: DIENSTPLAN_SET_ID,
    name: DIENSTPLAN_SET_NAME,
    createdAt: 0,
    sourceImageCount: 0,
    words: RAW_WORDS.map((word, index) => ({
      id: `${DIENSTPLAN_SET_ID}-${index}`,
      ...word,
    })),
    masteredWordIds: [],
  };
}