import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["die E-Mail", "e-mail", "noun"],
  ["die Hausverwaltung", "building management", "noun"],
  ["der Gliederungspunkt", "breakdown point", "noun"],
  ["der Einleitungssatz", "introduction", "noun"],
  ["sehr", "very", "adverb"],
  ["der Herr", "sir", "noun"],
  ["deshalb", "therefore", "adverb"],
  ["bitten", "to ask", "verb"],
  ["der Grund", "reason", "noun"],
  ["die Beanstandung", "complaint / objection", "noun"],
  ["die Firma", "company", "noun"],
  ["verständigen", "to communicate / notify", "verb"],
  ["schaden", "to damage", "verb"],
  ["das Schreiben", "letter", "noun"],
  ["der Montag", "monday", "noun"],
  ["der Freitag", "friday", "noun"],
  ["zwischen", "between", "other"],
  ["die Uhr", "clock / o'clock", "noun"],
  ["das Büro", "office", "noun"],
  ["der Bedarf", "need", "noun"],
  ["können", "to be able to", "verb"],
  ["die Schilderung", "description", "noun"],
  ["ander", "other", "adjective"],
  ["der Termin", "date / appointment", "noun"],
  ["vereinbaren", "to arrange / agree upon", "verb"],
  ["das Problem", "problem", "noun"],
  ["vor", "before", "other"],
  ["der Einzug", "move-in / collection", "noun"],
  ["die Kaffeeküche", "coffee kitchen", "noun"],
  ["leider", "unfortunately", "adverb"],
  ["der Boden", "ground / floor", "noun"],
  ["der Riss", "crack", "noun"],
  ["die Küche", "kitchen", "noun"],
  ["benutzen", "to use", "verb"],
  ["die Bitte", "request / please", "noun"],
  ["die Erledigung", "completion / handling", "noun"],
  ["soeben", "just now", "adverb"],
  ["besprechen", "to discuss", "verb"],
  ["ihnen", "to you", "other"],
  ["schriftlich", "in writing", "other"],
  ["schildern", "to describe", "verb"],
  ["die Erreichbarkeit", "accessibility", "noun"],
  ["das Telefongespräch", "telephone call", "noun"],
  ["viel", "much / many", "other"],
  ["der Dank", "thanks", "noun"],
  ["im Voraus", "in advance", "other"],
  ["die Anrede", "salutation", "noun"],
  ["freundlich", "friendly", "adjective"],
  ["grüßen", "to greet", "verb"],
  ["der Geschäftsführer", "managing director", "noun"],
  ["der Schluss", "conclusion", "noun"],
  ["der Gruß", "greetings", "noun"],
  ["der Punkt", "point", "noun"],
  ["erfinden", "to invent", "verb"],
  ["brauchen", "to need", "verb"],
  ["der Zweitschlüssel", "second key", "noun"],
  ["neu", "new", "adjective"],
  ["der Werkstattraum", "workshop room", "noun"],
  ["der Malerbetrieb", "painting business", "noun"],
  ["der Büroraum", "office space", "noun"],
  ["streichen", "to paint / delete", "verb"],
  ["möchten", "to want / would like", "verb"],
  ["die Nachbesserung", "improvement / rectification", "noun"],
  ["der Anruf", "call", "noun"],
  ["der Boiler", "boiler", "noun"],
  ["ausfallen", "to fail / be canceled", "verb"],
  ["die Nachricht", "message", "noun"],
  ["telefonisch", "by phone", "other"],
  ["einmal", "once", "adverb"],
  ["erinnern", "to remind / remember", "verb"],
  ["haben", "to have", "verb"],
  ["klären", "to clarify", "verb"],
  ["falls", "if", "other"],
  ["die Rückfrage", "query / follow-up question", "noun"],
  ["anrufen", "to call", "verb"],
  ["täglich", "daily", "other"],
  ["die Werkstatt", "workshop", "noun"],
  ["der Vorhang", "curtain", "noun"],
  ["gut", "good", "adjective"],
  ["der Tag", "day", "noun"],
  ["die Frau", "woman / Ms.", "noun"],
  ["die Situation", "situation", "noun"],
  ["planen", "to plan", "verb"],
  ["spielen", "to play", "verb"],
  ["der Dialog", "dialogue", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const EMAIL_HAUSVERWALTUNG_SET_ID = "db410b05-cd3c-4a41-bf0c-ba2a5dbee787";
export const EMAIL_HAUSVERWALTUNG_SET_NAME = "Kapitel 1 - Eine E-Mail an die Hausverwaltung";

export function getEmailHausverwaltungSet(): StudySet {
  return {
    id: EMAIL_HAUSVERWALTUNG_SET_ID,
    name: EMAIL_HAUSVERWALTUNG_SET_NAME,
    createdAt: 0,
    sourceImageCount: 1,
    words: RAW_WORDS.map((word, index) => ({ id: `${EMAIL_HAUSVERWALTUNG_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
