import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["das Gespräch", "conversation / talk", "noun"],
  ["das folgende Wort", "following word", "noun"],
  ["der Ausdruck", "expression", "noun"],
  ["ordnen", "to order / arrange", "verb"],
  ["der Kiosk", "kiosk", "noun"],
  ["betreiben", "to operate / run", "verb"],
  ["das Geschäft", "business / shop", "noun"],
  ["die Buchführung", "accounting / bookkeeping", "noun"],
  ["eröffnen", "to open", "verb"],
  ["der Lieferant", "supplier", "noun"],
  ["die Lieferantin", "female supplier", "noun"],
  ["der Besitzer", "owner", "noun"],
  ["die Besitzerin", "female owner", "noun"],
  ["die Filiale", "branch / subsidiary", "noun"],
  ["der Mietvertrag", "rental contract / lease", "noun"],
  ["gewerblich", "commercial / industrial", "adjective"],
  ["der Raum", "room / space", "noun"],
  ["die Lage", "location / situation", "noun"],
  ["die Ware", "goods / product", "noun"],
  ["der Pachtvertrag", "lease / rental contract", "noun"],
  ["die Auswahl", "selection / choice", "noun"],
  ["das Sortiment", "product range / assortment", "noun"],
  ["die Reserve", "reserve", "noun"],
  ["gründen", "to found / start", "verb"],
  ["die Kette", "chain", "noun"],
  ["geschäftig", "busy", "adjective"],
  ["der Businessplan", "business plan", "noun"],
  ["die Einnahme", "income / revenue", "noun"],
  ["die Ausgabe", "expense / output", "noun"],
  ["der Betrieb", "company / establishment", "noun"],
  ["die Rücklage", "reserve / savings", "noun"],
  ["das Konzept", "concept", "noun"],
  ["das Ziel", "goal / objective", "noun"],
  ["das Unternehmen", "company / enterprise", "noun"],
  ["die Verwirklichung", "realization / implementation", "noun"],
  ["der Minijob", "minijob / low-income job", "noun"],
  ["wichtig", "important", "adjective"],
  ["die Zeit", "time", "noun"],
  ["die Kundschaft", "clientele / clients", "noun"],
  ["der Kunde", "customer", "noun"],
  ["arbeitslos", "unemployed", "adjective"],
  ["ausprobieren", "to try out", "verb"],
  ["unzufrieden", "dissatisfied", "adjective"],
  ["die Arbeit", "work", "noun"],
  ["der Supermarkt", "supermarket", "noun"],
  ["eigen", "own", "adjective"],
  ["wovon", "of which / what from", "other"],
  ["der Anfang", "beginning / start", "noun"],
  ["die Tätigkeit", "activity / proceeding", "noun"],
  ["früh", "early", "adjective"],
  ["früher", "earlier / previous", "adverb"],
  ["der Vertrag", "contract", "noun"],
  ["die Arbeitserfahrung", "work experience", "noun"],
  ["selbstständig", "self-employed", "adjective"],
  ["die Versicherung", "insurance", "noun"],
  ["sich auskennen", "to know one's way around", "verb"],
  ["das Existenzgründerseminar", "start-up seminar", "noun"],
  ["die Geschäftsidee", "business idea", "noun"],
  ["mögen", "to like / would like", "verb"],
  ["der Beruf", "occupation / profession", "noun"],
  ["überlegen", "to think over / consider", "verb"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const GESPRAECH_MEHMET_SET_ID = "3c177345-1bbc-43a2-a5b8-e8c111cb95bf";
export const GESPRAECH_MEHMET_SET_NAME = "Kapitel 2 - Gespräch mit Mehmet";

export function getGespraechMehmetSet(): StudySet {
  return {
    id: GESPRAECH_MEHMET_SET_ID,
    name: GESPRAECH_MEHMET_SET_NAME,
    createdAt: 0,
    sourceImageCount: 0,
    words: RAW_WORDS.map((word, index) => ({
      id: `${GESPRAECH_MEHMET_SET_ID}-${index}`,
      ...word,
    })),
    masteredWordIds: [],
  };
}