import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["das Problem", "problem", "noun"],
  ["die Hausverwaltung", "property management / house management", "noun"],
  ["die Zeichnung", "drawing", "noun"],
  ["einmal", "once", "adverb"],
  ["das Büro", "office", "noun"],
  ["lassen", "to let / leave", "verb"],
  ["der Boden", "floor / ground", "noun"],
  ["der Riss", "crack", "noun"],
  ["fühlen", "to feel", "verb"],
  ["die Kaffeeküche", "coffee kitchen", "noun"],
  ["renovieren", "to renovate", "verb"],
  ["die Angst", "fear", "noun"],
  ["wirklich", "really", "other"],
  ["die Ordnung", "order", "noun"],
  ["die Küche", "kitchen", "noun"],
  ["benutzen", "to use", "verb"],
  ["schildern", "to describe / depict", "verb"],
  ["vorbeikommen", "to come by", "verb"],
  ["das Folgende", "the following", "noun"],
  ["bitten", "to ask / request", "verb"],
  ["natürlich", "of course / natural", "other"],
  ["das Problem", "problem", "noun"],
  ["die Werkstatt", "workshop", "noun"],
  ["der Arbeitsraum", "workspace", "noun"],
  ["die Türklinke", "door handle", "noun"],
  ["reparieren", "to repair", "verb"],
  ["lösen", "to solve / dissolve", "verb"],
  ["unten", "below / downstairs", "adverb"],
  ["abgehen", "to come off / detach", "verb"],
  ["anrufen", "to call", "verb"],
  ["die Zentralheizung", "central heating", "noun"],
  ["der Bescheid", "notice / information", "noun"],
  ["hochziehen", "to pull up", "verb"],
  ["werden", "to become / will", "verb"],
  ["der Abfluss", "drain", "noun"],
  ["das Spülbecken", "sink", "noun"],
  ["kümmern", "to care / look after", "verb"],
  ["der Rollladen", "roll-out shutter / roller blind", "noun"],
  ["der Aufzug", "elevator", "noun"],
  ["der Topf", "pot", "noun"],
  ["der Abflussreiniger", "drain cleaner", "noun"],
  ["verwenden", "to use", "verb"],
  ["die Tür", "door", "noun"],
  ["der Aktenschrank", "file cabinet", "noun"],
  ["anschrauben", "to screw on", "verb"],
  ["der Wasserhahn", "faucet / tap", "noun"],
  ["die Toilette", "toilet", "noun"],
  ["der Handwerker", "craftsman", "noun"],
  ["das Türschloss", "door lock", "noun"],
  ["abbrechen", "to break off / cancel", "verb"],
  ["der Hausmeister", "caretaker / janitor", "noun"],
  ["spielen", "to play", "verb"],
  ["der Dialog", "dialogue", "noun"],
  ["der Vermieter", "landlord / owner", "noun"],
  ["der Mieter", "tenant", "noun"],
  ["der Apparat", "apparatus / phone", "noun"],
  ["der Dank", "thanks", "noun"],
  ["der Dank", "thanks", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const PROBLEM_SET_ID = "a5441fb1-8899-4efb-843b-f568be8a4df7";
export const PROBLEM_SET_NAME = "Kapitel 1 - Problem";

export function getProblemSet(): StudySet {
  return {
    id: PROBLEM_SET_ID,
    name: PROBLEM_SET_NAME,
    createdAt: 0,
    sourceImageCount: 1,
    words: RAW_WORDS.map((word, index) => ({ id: `${PROBLEM_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
