import { getReiseangeboteSet } from "@/lib/reiseangeboteData";

interface GapTestQuestion {
  sentence: string;
  translation: string;
  answer: string;
  wordId: string;
}

const PROMPTS: { word: string; sentence: string; translation: string; answer: string }[] = [
  { word: "der Touri", sentence: "Viele ______ besuchen im Sommer die Strände am Mittelmeer.", translation: "Many tourists visit the beaches of the Mediterranean in summer.", answer: "Touris" },
  { word: "das Reiseangebot", sentence: "Das ______ des Reisebüros umfasst Hotels, Flüge und Ausflüge.", translation: "The travel offer from the travel agency includes hotels, flights, and excursions.", answer: "Reiseangebot" },
  { word: "anzeigen", sentence: "Die Website ______ verschiedene Hotels mit ihren Preisen ______.", translation: "The website displays various hotels with their prices.", answer: "zeigt an" },
  { word: "das Angebot", sentence: "Dieses ______ ist besonders günstig, weil der Flug im Preis enthalten ist.", translation: "This offer is particularly inexpensive because the flight is included in the price.", answer: "Angebot" },
  { word: "die Dame", sentence: "Die ______ am Empfang hilft uns bei der Buchung.", translation: "The lady at reception helps us with the booking.", answer: "Dame" },
  { word: "der Herr", sentence: "Der ______ möchte ein Einzelzimmer für drei Nächte reservieren.", translation: "The gentleman would like to reserve a single room for three nights.", answer: "Herr" },
  { word: "das Mittelmeer", sentence: "Viele Urlauber verbringen ihre Ferien am ______.", translation: "Many holidaymakers spend their vacation on the Mediterranean.", answer: "Mittelmeer" },
  { word: "wobei", sentence: "Wir haben ein Hotel mit Meerblick gebucht, ______ uns die ruhige Lage besonders wichtig war.", translation: "We booked a hotel with a sea view, whereby the quiet location was particularly important to us.", answer: "wobei" },
  { word: "erholen", sentence: "Im Urlaub möchte ich mich von meinem stressigen Arbeitsalltag ______.", translation: "On vacation, I want to recover from my stressful working life.", answer: "erholen" },
  { word: "eher", sentence: "Ich mache ______ einen Aktivurlaub als einen reinen Strandurlaub.", translation: "I would rather take an active holiday than a purely beach holiday.", answer: "eher" },
  { word: "sportlich", sentence: "Für ______ Urlauber bietet das Hotel Tennis, Schwimmen und Fahrradtouren an.", translation: "For sporty holidaymakers, the hotel offers tennis, swimming, and cycling tours.", answer: "sportliche" },
  { word: "die Entspannung", sentence: "Nach einer anstrengenden Arbeitswoche brauche ich vor allem ______.", translation: "After a tiring working week, I mainly need relaxation.", answer: "Entspannung" },
  { word: "die Ruhe", sentence: "Wir haben ein Hotel auf dem Land gebucht, weil wir ______ suchen.", translation: "We booked a hotel in the countryside because we are looking for peace and quiet.", answer: "Ruhe" },
  { word: "die Strandnähe", sentence: "Bei der Hotelsuche ist mir die ______ besonders wichtig.", translation: "When looking for a hotel, proximity to the beach is particularly important to me.", answer: "Strandnähe" },
  { word: "befinden", sentence: "Das Hotel ______ sich direkt am Meer.", translation: "The hotel is located directly by the sea.", answer: "befindet" },
  { word: "der Pool", sentence: "An heißen Tagen verbringen viele Gäste ihre Zeit am ______.", translation: "On hot days, many guests spend their time by the pool.", answer: "Pool" },
  { word: "verfügen", sentence: "Das Hotel ______ über einen großen Garten und einen beheizten Pool.", translation: "The hotel has a large garden and a heated pool.", answer: "verfügt" },
  { word: "der Wert", sentence: "Das Hotel bietet ein gutes Preis-Leistungs-______.", translation: "The hotel offers good value for money.", answer: "Wert" },
  { word: "das Animationsprogramm", sentence: "Das ______ des Hotels umfasst Spiele, Sport und Abendveranstaltungen.", translation: "The hotel's entertainment program includes games, sports, and evening events.", answer: "Animationsprogramm" },
  { word: "zukommen", sentence: "Auf die Gäste ______ während der Reise einige Überraschungen ______.", translation: "The guests can expect a few surprises during the trip.", answer: "kommen zu" },
  { word: "lassen", sentence: "Im Urlaub möchte ich mein Handy öfter zu Hause ______.", translation: "On vacation, I want to leave my phone at home more often.", answer: "lassen" },
  { word: "der Frühbucherrabatt", sentence: "Wenn Sie früh buchen, erhalten Sie einen ______.", translation: "If you book early, you receive an early booking discount.", answer: "Frühbucherrabatt" },
  { word: "die Pauschalreise", sentence: "Bei einer ______ sind Flug und Hotel normalerweise zusammen gebucht.", translation: "With a package holiday, the flight and hotel are usually booked together.", answer: "Pauschalreise" },
  { word: "die Individualreise", sentence: "Bei einer ______ kann man die Route und die Unterkünfte selbst auswählen.", translation: "With an independent trip, you can choose the route and accommodation yourself.", answer: "Individualreise" },
  { word: "das Interesse", sentence: "Ich habe großes ______ an Kulturreisen und historischen Städten.", translation: "I have a great interest in cultural trips and historic cities.", answer: "Interesse" },
  { word: "anhängen", sentence: "Bitte ______ Sie die Buchungsbestätigung an Ihre E-Mail ______.", translation: "Please attach the booking confirmation to your email.", answer: "hängen an" },
  { word: "das Reiseprogramm", sentence: "Das ______ enthält alle geplanten Ausflüge und Besichtigungen.", translation: "The travel itinerary contains all planned excursions and sightseeing activities.", answer: "Reiseprogramm" },
  { word: "das Pauschalangebot", sentence: "Das ______ beinhaltet sieben Übernachtungen und den Hin- und Rückflug.", translation: "The package deal includes seven nights and a return flight.", answer: "Pauschalangebot" },
  { word: "besonders", sentence: "Im Frühling ist die Insel ______ schön.", translation: "The island is especially beautiful in spring.", answer: "besonders" },
  { word: "hinweisen", sentence: "Der Reiseleiter möchte die Gäste auf die geänderte Abfahrtszeit ______.", translation: "The tour guide wants to point out the changed departure time to the guests.", answer: "hinweisen" },
  { word: "die Insel", sentence: "Auf der ______ gibt es viele kleine Dörfer und schöne Strände.", translation: "There are many small villages and beautiful beaches on the island.", answer: "Insel" },
  { word: "das Programm", sentence: "Das abwechslungsreiche ______ bietet Aktivitäten für Kinder und Erwachsene.", translation: "The varied program offers activities for children and adults.", answer: "Programm" },
  { word: "die Städtereise", sentence: "Für das lange Wochenende planen wir eine ______ nach Wien.", translation: "We are planning a city trip to Vienna for the long weekend.", answer: "Städtereise" },
  { word: "der Campingurlaub", sentence: "Bei einem ______ übernachten wir im Zelt und kochen selbst.", translation: "On a camping holiday, we sleep in a tent and cook for ourselves.", answer: "Campingurlaub" },
  { word: "die Fahrradtour", sentence: "Bei schönem Wetter machen wir eine ______ entlang des Flusses.", translation: "In good weather, we go on a cycling tour along the river.", answer: "Fahrradtour" },
  { word: "der Sonnenschein", sentence: "Bei strahlendem ______ macht ein Spaziergang am Strand besonders viel Spaß.", translation: "A walk on the beach is especially enjoyable in bright sunshine.", answer: "Sonnenschein" },
  { word: "die Reise", sentence: "Unsere ______ nach Griechenland beginnt am Montag.", translation: "Our trip to Greece begins on Monday.", answer: "Reise" },
  { word: "die Boutique", sentence: "In einer kleinen ______ in der Altstadt kann man besondere Kleidung kaufen.", translation: "You can buy special clothing in a small boutique in the old town.", answer: "Boutique" },
  { word: "der Kundenwunsch", sentence: "Ein gutes Reisebüro versucht, jeden ______ zu berücksichtigen.", translation: "A good travel agency tries to take every customer request into account.", answer: "Kundenwunsch" },
  { word: "die Sonne", sentence: "Im Urlaub möchte ich am Strand liegen und die ______ genießen.", translation: "On vacation, I want to lie on the beach and enjoy the sun.", answer: "Sonne" },
  { word: "das Meer", sentence: "Vom Hotelzimmer aus können wir direkt auf das ______ schauen.", translation: "From the hotel room, we can look directly out at the sea.", answer: "Meer" },
  { word: "das Resort", sentence: "Das luxuriöse ______ verfügt über mehrere Restaurants und einen Wellnessbereich.", translation: "The luxurious resort has several restaurants and a wellness area.", answer: "Resort" },
  { word: "genießen", sentence: "Im Urlaub möchte ich gutes Essen und die schöne Landschaft ______.", translation: "On vacation, I want to enjoy good food and beautiful scenery.", answer: "genießen" },
  { word: "das Zimmer", sentence: "Wir möchten ein ruhiges ______ mit Balkon reservieren.", translation: "We would like to reserve a quiet room with a balcony.", answer: "Zimmer" },
  { word: "sonnen", sentence: "Viele Gäste ______ sich am Pool, während andere schwimmen.", translation: "Many guests sunbathe by the pool while others swim.", answer: "sonnen" },
  { word: "die Hotelanlage", sentence: "Die ______ umfasst mehrere Gebäude, einen Garten und einen großen Pool.", translation: "The hotel complex includes several buildings, a garden, and a large pool.", answer: "Hotelanlage" },
  { word: "der Geschmack", sentence: "Bei der Wahl des Hotels kommt es auch auf den persönlichen ______ an.", translation: "When choosing a hotel, personal taste also matters.", answer: "Geschmack" },
  { word: "die Ägäis", sentence: "Viele Urlauber verbringen ihre Ferien an der ______ in Griechenland.", translation: "Many holidaymakers spend their vacation on the Aegean Sea in Greece.", answer: "Ägäis" },
  { word: "der Ausdruck", sentence: "Der ______ „All-inclusive“ bedeutet, dass viele Leistungen im Preis enthalten sind.", translation: "The expression “all-inclusive” means that many services are included in the price.", answer: "Ausdruck" },
  { word: "vergleichen", sentence: "Vor der Buchung sollten wir die Preise verschiedener Hotels ______.", translation: "Before booking, we should compare the prices of different hotels.", answer: "vergleichen" },
  { word: "die Halbpension", sentence: "Bei der ______ sind Frühstück und eine weitere Hauptmahlzeit inbegriffen.", translation: "With half board, breakfast and one other main meal are included.", answer: "Halbpension" },
  { word: "das Frühstück", sentence: "Das ______ wird jeden Morgen von sieben bis zehn Uhr serviert.", translation: "Breakfast is served every morning from seven to ten.", answer: "Frühstück" },
  { word: "das Erlebnis", sentence: "Die Bootsfahrt bei Sonnenuntergang war ein unvergessliches ______.", translation: "The boat trip at sunset was an unforgettable experience.", answer: "Erlebnis" },
  { word: "magisch", sentence: "Die beleuchtete Altstadt wirkt am Abend einfach ______.", translation: "The illuminated old town looks simply magical in the evening.", answer: "magisch" },
  { word: "der Garten", sentence: "Die Gäste können im großen ______ entspannen und die Blumen bewundern.", translation: "Guests can relax in the large garden and admire the flowers.", answer: "Garten" },
  { word: "das Unterhaltungsangebot", sentence: "Das ______ des Hotels reicht von Live-Musik bis zu Tanzveranstaltungen.", translation: "The hotel's entertainment options range from live music to dance events.", answer: "Unterhaltungsangebot" },
  { word: "buchbar", sentence: "Das Hotel ist von Mai bis Oktober ______.", translation: "The hotel is available for booking from May to October.", answer: "buchbar" },
  { word: "der Flug", sentence: "Unser ______ nach Athen startet morgen früh um acht Uhr.", translation: "Our flight to Athens departs tomorrow morning at eight.", answer: "Flug" },
  { word: "der Transfer", sentence: "Der ______ vom Flughafen zum Hotel ist im Preis enthalten.", translation: "The transfer from the airport to the hotel is included in the price.", answer: "Transfer" },
  { word: "der Inklusivpreis", sentence: "Im ______ sind die Übernachtung, das Frühstück und der Transfer enthalten.", translation: "The inclusive price covers accommodation, breakfast, and the transfer.", answer: "Inklusivpreis" },
  { word: "die Vollpension", sentence: "Bei der ______ sind Frühstück, Mittagessen und Abendessen im Preis enthalten.", translation: "With full board, breakfast, lunch, and dinner are included in the price.", answer: "Vollpension" },
  { word: "die Art", sentence: "Welche ______ von Urlaub bevorzugen Sie: Strandurlaub oder Aktivurlaub?", translation: "What type of holiday do you prefer: a beach holiday or an active holiday?", answer: "Art" },
  { word: "haken", sentence: "Bei der Online-Buchung kann es manchmal an der Bezahlung ______.", translation: "Sometimes something can go wrong with the payment during online booking.", answer: "haken" },
  { word: "die Gebühr", sentence: "Für die Stornierung der Reise fällt eine zusätzliche ______ an.", translation: "An additional fee applies for cancelling the trip.", answer: "Gebühr" },
  { word: "der Zeitraum", sentence: "Für welchen ______ möchten Sie das Hotel buchen?", translation: "For what period would you like to book the hotel?", answer: "Zeitraum" },
  { word: "die Anzahlung", sentence: "Bei der Buchung müssen wir eine ______ von 20 Prozent bezahlen.", translation: "When booking, we have to pay a deposit of 20 percent.", answer: "Anzahlung" },
  { word: "überweisen", sentence: "Bitte ______ Sie die Anzahlung innerhalb von sieben Tagen auf unser Konto.", translation: "Please transfer the deposit to our account within seven days.", answer: "überweisen" },
  { word: "das Konto", sentence: "Der Reisepreis wird direkt von unserem ______ abgebucht.", translation: "The travel price is debited directly from our account.", answer: "Konto" },
  { word: "erhalten", sentence: "Nach der Buchung ______ Sie eine Bestätigung per E-Mail.", translation: "After booking, you will receive a confirmation by email.", answer: "erhalten" },
  { word: "die Notiz", sentence: "Ich mache mir eine kurze ______, damit ich die Abfahrtszeit nicht vergesse.", translation: "I make a brief note so that I don't forget the departure time.", answer: "Notiz" },
  { word: "ergänzen", sentence: "Bitte ______ Sie Ihre persönlichen Daten im Buchungsformular.", translation: "Please complete your personal details in the booking form.", answer: "ergänzen" },
  { word: "der Satz", sentence: "Bitte formulieren Sie einen vollständigen ______ mit dem neuen Wort.", translation: "Please form a complete sentence with the new word.", answer: "Satz" },
  { word: "der Urlaub", sentence: "Im ______ möchte ich neue Orte entdecken und mich erholen.", translation: "On vacation, I want to discover new places and relax.", answer: "Urlaub" },
  { word: "die Reisegruppe", sentence: "Die ______ trifft sich um neun Uhr vor dem Hotel.", translation: "The tour group meets in front of the hotel at nine o'clock.", answer: "Reisegruppe" },
  { word: "diskutieren", sentence: "Die Reisenden ______ darüber, welches Ausflugsziel sie besuchen möchten.", translation: "The travellers discuss which destination they would like to visit.", answer: "diskutieren" },
  { word: "der Alltag", sentence: "Eine Reise hilft mir, Abstand vom stressigen ______ zu gewinnen.", translation: "A trip helps me get some distance from stressful everyday life.", answer: "Alltag" },
  { word: "die Kompetenz", sentence: "Gute Sprachkenntnisse sind eine wichtige ______ für einen Reiseleiter.", translation: "Good language skills are an important competence for a tour guide.", answer: "Kompetenz" },
  { word: "die Reiseerfahrung", sentence: "Durch ihre langjährige ______ kennt sie viele interessante Reiseziele.", translation: "Through her many years of travel experience, she knows many interesting destinations.", answer: "Reiseerfahrung" },
  { word: "das Reisebüro", sentence: "Im ______ können Kunden verschiedene Urlaubsangebote vergleichen und buchen.", translation: "At the travel agency, customers can compare and book different holiday offers.", answer: "Reisebüro" },
  { word: "schriftlich", sentence: "Bitte bestätigen Sie Ihre Buchung ______ per E-Mail.", translation: "Please confirm your booking in writing by email.", answer: "schriftlich" },
  { word: "der Bezug", sentence: "In Ihrer E-Mail fehlt der ______ zu unserer vorherigen Anfrage.", translation: "Your email is missing the reference to our previous inquiry.", answer: "Bezug" },
  { word: "die Reiseform", sentence: "Welche ______ passt am besten zu Ihren Bedürfnissen: eine Pauschalreise oder eine Individualreise?", translation: "Which form of travel best suits your needs: a package holiday or an independent trip?", answer: "Reiseform" },
  { word: "der Ratschlag", sentence: "Mein ______ ist, die Reise frühzeitig zu buchen.", translation: "My advice is to book the trip early.", answer: "Ratschlag" },
  { word: "der Grund", sentence: "Was ist der ______ für Ihre Entscheidung, dieses Hotel zu wählen?", translation: "What is the reason for your decision to choose this hotel?", answer: "Grund" },
  { word: "folgen", sentence: "Nach der Buchung ______ weitere Informationen per E-Mail.", translation: "Further information follows by email after the booking.", answer: "folgen" },
  { word: "nennen", sentence: "Können Sie mir bitte drei empfehlenswerte Hotels ______?", translation: "Could you name three recommended hotels for me?", answer: "nennen" },
  { word: "telefonisch", sentence: "Bei Fragen können Sie uns jederzeit ______ erreichen.", translation: "If you have any questions, you can reach us by phone at any time.", answer: "telefonisch" },
  { word: "die Anzeige", sentence: "In der ______ werden günstige Flüge nach Spanien beworben.", translation: "The advertisement promotes cheap flights to Spain.", answer: "Anzeige" },
  { word: "das Modell", sentence: "Das Reisebüro bietet ein neues ______ für flexible Urlaubsbuchungen an.", translation: "The travel agency offers a new model for flexible holiday bookings.", answer: "Modell" },
  { word: "die Bewerbung", sentence: "Für die Stelle als Reiseleiterin muss sie eine ______ schreiben.", translation: "She has to write an application for the position of tour guide.", answer: "Bewerbung" },
  { word: "einholen", sentence: "Vor der Buchung sollten wir mehrere Angebote ______.", translation: "Before booking, we should obtain several offers.", answer: "einholen" },
  { word: "das Informationsgespräch", sentence: "Vor der Reise findet ein ______ statt, bei dem alle wichtigen Fragen geklärt werden.", translation: "Before the trip, there is an information meeting where all important questions are clarified.", answer: "Informationsgespräch" },
  { word: "der Beruf", sentence: "Der ______ des Reiseleiters erfordert gute Sprachkenntnisse und Organisationstalent.", translation: "The profession of a tour guide requires good language skills and organizational talent.", answer: "Beruf" },
  { word: "der Tourismus", sentence: "Der ______ ist für viele Regionen eine wichtige Einnahmequelle.", translation: "Tourism is an important source of income for many regions.", answer: "Tourismus" },
  { word: "die Stellenanzeige", sentence: "In der ______ werden die Aufgaben und Anforderungen der Stelle beschrieben.", translation: "The job advertisement describes the duties and requirements of the position.", answer: "Stellenanzeige" },
  { word: "satirisch", sentence: "Der Artikel beschreibt die Probleme im Massentourismus auf ______ Weise.", translation: "The article describes the problems of mass tourism in a satirical way.", answer: "satirische" },
  { word: "das Berufsbild", sentence: "Das ______ eines Reiseleiters umfasst die Betreuung und Information der Reisenden.", translation: "The occupational profile of a tour guide includes looking after and informing travellers.", answer: "Berufsbild" },
  { word: "der Reiseleiter", sentence: "Der ______ erklärt der Gruppe die Geschichte der Stadt und zeigt die wichtigsten Sehenswürdigkeiten.", translation: "The tour guide explains the city's history to the group and shows them the main sights.", answer: "Reiseleiter" },
];

const sourceWords = getReiseangeboteSet().words;
const wordsByGerman = new Map(sourceWords.map((word) => [word.german.toLowerCase(), word]));

export const REISEANGEBOTE_GAP_TEST: GapTestQuestion[] = PROMPTS.map((prompt) => {
  const word = wordsByGerman.get(prompt.word.toLowerCase());
  if (!word) throw new Error(`No Reiseangebote vocabulary word found for: ${prompt.word}`);
  return { ...prompt, wordId: word.id };
});