import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["der Späti", "late-night kiosk", "noun"],
  ["der Blogeintrag", "blog entry", "noun"],
  ["der Kommentar", "comment", "noun"],
  ["notieren", "to note down", "verb"],
  ["informieren", "to inform", "verb"],
  ["die Themenkarte", "theme card", "noun"],
  ["tauschen", "to exchange", "verb"],
  ["das Warenangebot", "supply of goods", "noun"],
  ["der Treffpunkt", "meeting point", "noun"],
  ["der Lärm", "noise", "noun"],
  ["die Öffnungszeit", "opening time", "noun"],
  ["die Arbeitszeit", "working hours", "noun"],
  ["der Blog", "blog", "noun"],
  ["vorstellen", "to introduce / present", "verb"],
  ["die Ecke", "corner", "noun"],
  ["der Leser", "reader", "noun"],
  ["nennen", "to name", "verb"],
  ["laden", "to load / invite", "verb"],
  ["der Kiosk", "kiosk", "noun"],
  ["das Geschäft", "business / shop", "noun"],
  ["nämlich", "namely / of which", "adverb"],
  ["der Spätkauf", "late-night grocery shop", "noun"],
  ["eigentlich", "actually", "adverb"],
  ["der Alltag", "daily life", "noun"],
  ["die Auswahl", "selection", "noun"],
  ["fehlen", "to be missing", "verb"],
  ["die Windel", "diaper", "noun"],
  ["das Baby", "baby", "noun"],
  ["die Lösung", "solution", "noun"],
  ["natürlich", "of course / natural", "adjective"],
  ["das Ding", "thing", "noun"],
  ["das Herz", "heart", "noun"],
  ["gewöhnlich", "common / usual", "adjective"],
  ["die Zeitung", "newspaper", "noun"],
  ["die Zeitschrift", "periodical / magazine", "noun"],
  ["die Süßigkeit", "sweet / candy", "noun"],
  ["der Knabberartikel", "snack / nibble", "noun"],
  ["bereiten", "to prepare", "verb"],
  ["die Sache", "item / thing", "noun"],
  ["der kleine Laden", "small shop", "noun"],
  ["frisch", "fresh", "adjective"],
  ["das Einkaufsparadies", "shopping paradise", "noun"],
  ["gern", "gladly / like to", "adverb"],
  ["die Besorgung", "errand / supply", "noun"],
  ["die Sommernacht", "summer night", "noun"],
  ["der Nachbar", "neighbour", "noun"],
  ["der Einheimische", "local", "noun"],
  ["das Zuhause", "home", "noun"],
  ["das Ohr", "ear", "noun"],
  ["der Kunde", "customer", "noun"],
  ["persönlich", "personal", "adjective"],
  ["die Entdeckung", "discovery", "noun"],
  ["schlechthin", "par excellence / sheer", "adverb"],
  ["der Abend", "evening", "noun"],
  ["der Supermarkt", "supermarket", "noun"],
  ["hetzen", "to rush / hustle", "verb"],
  ["die Journalistin", "female journalist", "noun"],
  ["die Bloggerin", "female blogger", "noun"],
  ["klar", "clear", "adjective"],
  ["freiberuflich", "freelance", "adjective"],
  ["einteilen", "to divide / organize", "verb"],
  ["der Auftrag", "mission / assignment", "noun"],
  ["werden", "to become / will", "verb"],
  ["der Computer", "computer", "noun"],
  ["wenn", "if / when", "other"],
  ["fertig", "finished", "adjective"],
  ["geschlossen", "closed", "adjective"],
  ["der Magen", "stomach", "noun"],
  ["der Abendausflug", "evening excursion", "noun"],
  ["zufällig", "random / by chance", "adjective"],
  ["die Umgebung", "environment / surroundings", "noun"],
  ["bisschen", "a little", "adverb"],
  ["unterhalten", "to converse / maintain", "verb"],
  ["hin", "there / towards", "adverb"],
  ["die Gleitzeit", "flextime", "noun"],
  ["anfangen", "to start", "verb"],
  ["der Kaffee", "coffee", "noun"],
  ["der Fruchtsaft", "fruit juice", "noun"],
  ["schade", "too bad", "adjective"],
  ["die Straße", "road / street", "noun"],
  ["der Schichtdienst", "shift work", "noun"],
  ["die Spätschicht", "late shift", "noun"],
  ["die Milch", "milk", "noun"],
  ["nächste", "next", "adjective"],
  ["holen", "to fetch", "verb"],
  ["die Schuld", "debt / fault", "noun"],
  ["der Kioskbesitzer", "kiosk owner", "noun"],
  ["die Nachtzeit", "nighttime", "noun"],
  ["außerdem", "in addition", "adverb"],
  ["der Verkäufer", "salesman", "noun"],
  ["die Verkäuferin", "saleswoman", "noun"],
  ["der Feierabend", "time off / end of the workday", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const SPAETI_SET_ID = "47750658-e914-4fc9-9f66-ec00db98d8c2";
export const SPAETI_SET_NAME = "Kapitel 2 - Späti";

export function getSpaetiSet(): StudySet {
  return {
    id: SPAETI_SET_ID,
    name: SPAETI_SET_NAME,
    createdAt: 0,
    sourceImageCount: 0,
    words: RAW_WORDS.map((word, index) => ({
      id: `${SPAETI_SET_ID}-${index}`,
      ...word,
    })),
    masteredWordIds: [],
  };
}