import { StudySet, VocabWord } from "./types";

const RAW_WORDS: ([string, string, string] | null)[] = [
  ["der Partyservice", "party service", "noun"],
  ["der Arbeitstag", "working day", "noun"],
  null,
  null,
  ["die Aussage", "statement", "noun"],
  ["der Artikel", "article", "noun"],
  ["der Abschnitt", "section", "noun"],
  null,
  ["führen", "to lead", "verb"],
  ["informieren", "to inform", "verb"],
  null,
  ["die Vorgesetzte", "female superior / head", "noun"],
  null,
  null,
  null,
  ["die Vorsicht", "caution", "noun"],
  ["das Gerücht", "rumor", "noun"],
  ["bringen", "to bring", "verb"],
  ["der frische Wind", "fresh air / wind", "noun"],
  ["vorsichtig", "careful", "adjective"],
  ["die Kritik", "criticism", "noun"],
  ["die Angst", "fear", "noun"],
  ["der Fehler", "error / mistake", "noun"],
  ["der Anfang", "beginning / start", "noun"],
  null,
  ["fangen", "to catch", "verb"],
  null,
  ["die Arbeit", "work", "noun"],
  ["die Absprache", "agreement", "noun"],
  null,
  ["eingenommen", "taken / biased", "adjective"],
  null,
  ["die Zusammenarbeit", "cooperation", "noun"],
  ["sicher", "sure / safe", "other"],
  ["der Grund", "reason", "noun"],
  ["das Verhalten", "behavior", "noun"],
  ["vielleicht", "maybe", "adverb"],
  ["starten", "to start", "verb"],
  ["der Vorgesetzte", "superior", "noun"],
  null,
  null,
  null,
  ["die Kollegin", "female colleague", "noun"],
  ["der Verbesserungsvorschlag", "proposal for improvement", "noun"],
  ["ändern", "to change", "verb"],
  null,
  ["hören", "to hear / listen", "verb"],
  ["der Kunde", "customer", "noun"],
  ["die Vorstellung", "presentation", "noun"],
  ["fragen", "to ask", "verb"],
  ["die Rundmail", "roundmail / circular email", "noun"],
  ["das Teammitglied", "team member", "noun"],
  null,
  null,
  ["peinlich", "embarrassing", "adjective"],
  ["hinterlassen", "to leave", "verb"],
  null,
  null,
  null,
  null,
  ["locker", "loose / casual", "adjective"],
  ["der Ton", "tone / sound", "noun"],
  null,
  ["die Ehrlichkeit", "honesty", "noun"],
  ["der Fall", "case", "noun"],
  null,
  ["vertuschen", "to cover up", "verb"],
  ["missverstanden", "misunderstood", "adjective"],
  ["unsicher", "uncertain / insecure", "other"],
  null,
  null,
  ["völlig", "completely / total", "other"],
  null,
  ["der Klatsch", "gossip", "noun"],
  ["der Tratsch", "gossip / chatter", "noun"],
  ["die Unterstützung", "support", "noun"],
  null,
  null,
  null,
  ["ersetzen", "to replace", "verb"],
  ["ordnen", "to order / arrange", "verb"],
  ["fehlerlos", "errorless / flawless", "adjective"],
  ["der Ratschlag", "advice", "noun"],
  ["die Hilfe", "help", "noun"],
  ["die Abmachung", "arrangement / agreement", "noun"],
  ["der Kundenkontakt", "customer contact", "noun"],
  null,
  ["ausdrücken", "to express", "verb"],
  null,
  null,
  null,
  null,
  ["markieren", "to mark", "verb"],
  null,
  ["ergänzen", "to add / complete", "verb"],
  ["die Form", "form", "noun"],
  null,
  null,
  ["der Fokus", "focus", "noun"],
  null,
  null,
  null,
  null,
  null,
  null,
  ["bilden", "to form", "verb"],
  null,
  ["freundlich", "friendly", "adjective"],
  ["begrüßen", "to welcome", "verb"],
  ["das Computersystem", "computer system", "noun"],
  ["erklären", "to explain", "verb"],
  ["die Beratung", "consultation / advice", "noun"],
  ["bitten", "to ask / request", "verb"],
  ["der Dienstplan", "work schedule", "noun"],
  null,
  null,
  ["die IT-Beauftragte", "IT representative", "noun"],
  ["der Arbeitsauftrag", "work order", "noun"],
  ["die Teeküche", "tea kitchen", "noun"],
  ["zeigen", "to show", "verb"],
  ["die Kundin", "female customer", "noun"],
  ["der Hausmeister", "caretaker", "noun"],
  ["das Zeiterfassungssystem", "time recording system", "noun"],
  ["gegeben", "given", "adjective"],
  ["vorstellen", "to present / introduce", "verb"],
  null,
  ["notieren", "to note down", "verb"],
  ["der Stichpunkt", "key point", "noun"],
  ["der Werdegang", "career path", "noun"],
  ["vergleichen", "to compare", "verb"],
  ["der Betreff", "subject line", "noun"],
  ["die Ansprechpartnerin", "female contact person", "noun"],
  null,
  ["der Lieferant", "supplier", "noun"],
  ["die Lieferantin", "female supplier", "noun"],
  null,
  null,
  null,
  null,
  null,
  null,
  ["die Leidenschaft", "passion", "noun"],
  null,
  ["außerdem", "in addition", "adverb"],
  null,
  ["zusammen", "together", "adverb"],
  ["die Ausbildung", "training / education", "noun"],
  ["die Restaurantfachfrau", "restaurant specialist", "noun"],
  ["das Café", "café", "noun"],
  ["die Organisation", "organization", "noun"],
  ["die Buchhaltung", "accounting", "noun"],
  ["die Kundenkommunikation", "customer communication", "noun"],
  ["kennenlernen", "to get to know", "verb"],
  null,
  ["wählen", "to choose / select", "verb"],
  ["bearbeiten", "to process / edit", "verb"],
  null,
  ["die Information", "information", "noun"],
  ["die Schrift", "writing / script", "noun"],
  ["die Aufgabe", "task", "noun"],
  null,
  ["umgekehrt", "vice versa", "other"],
  ["zwingen", "force, make smb do smth", "other"],
  ["überfordert", "overwhelmed", "other"],
  ["überlastet", "overwhelmed with amount of work", "other"],
  ["unangenehm", "unpleasant", "other"],
  ["zurückhaltend", "cautious", "other"],
  ["aufgeregt", "nervös", "other"],
  ["loben", "praise", "other"],
  ["bisherig", "previous", "other"],
  ["mitteilen", "share", "other"],
  ["unvoreingenommen", "unbiased", "other"],
  ["verlangen", "demand", "other"],
  ["sich anstrengen", "make an effort", "verb"],
  ["weiterkommen", "get ahead", "verb"],
  ["die Entscheidungen treffen", "make decisions", "verb"],
  ["überhäufen", "overwhelm", "verb"],
  ["Vorurteile", "prejudices", "noun"],
  ["gelassen", "relaxed", "adjective"],
  ["verhindern", "prevent", "verb"],
  ["Auftrag vergeben", "assign a task", "verb"],
  ["beurteilen", "to assess", "verb"],
  ["der Arbeitsablauf", "workflow", "noun"],
];

export const TEAMARBEIT_SET_ID = "faeeb4c0-21bd-4219-9b81-ad877466e128";
export const TEAMARBEIT_SET_NAME = "Kapitel 3 - Teamarbeit";

export function getTeamarbeitSet(): StudySet {
  return {
    id: TEAMARBEIT_SET_ID,
    name: TEAMARBEIT_SET_NAME,
    createdAt: 0,
    sourceImageCount: 1,
    words: RAW_WORDS.flatMap((word, index) => word ? [{ id: `${TEAMARBEIT_SET_ID}-${index}`, german: word[0], english: word[1], pos: word[2], example: "" }] : []),
    masteredWordIds: [],
  };
}
