import { getTeamrolleSet } from "@/lib/teamrolleData";

interface GapTestQuestion {
  sentence: string;
  translation: string;
  answer: string;
  wordId: string;
}

const PROMPTS: Omit<GapTestQuestion, "wordId">[] = [
  { sentence: "Jeder Mitarbeiter muss seine ______ im Team kennen.", translation: "Every employee needs to know their team role.", answer: "Teamrolle" },
  { sentence: "In der ______ erklärt die Projektleiterin kurz das Ziel der Besprechung.", translation: "In the introduction, the project manager briefly explains the goal of the meeting.", answer: "Einleitung" },
  { sentence: "Damit die Zusammenarbeit gut ______, müssen alle Informationen rechtzeitig teilen.", translation: "For the collaboration to work, everyone has to share information on time.", answer: "funktioniert" },
  { sentence: "______ im Team übernimmt einen Teil der Aufgabe.", translation: "Everyone in the team takes on part of the task.", answer: "Jeder" },
  { sentence: "Die ______ der neuen Aufgabe ist noch nicht ganz klar.", translation: "The description of the new task is not completely clear yet.", answer: "Beschreibung" },
  { sentence: "Welche ______ übernimmt Anna bei diesem Projekt?", translation: "Which role will Anna take on in this project?", answer: "Rolle" },
  { sentence: "Am Ende der Besprechung möchte die Teamleiterin das Thema ______.", translation: "At the end of the meeting, the team leader wants to close the topic.", answer: "schließen" },
  { sentence: "Können Sie bitte kurz ______, welche Aufgaben Sie im Team übernehmen?", translation: "Could you briefly describe which tasks you take on in the team?", answer: "beschreiben" },
  { sentence: "Unsere ______ arbeitet seit drei Monaten an diesem Projekt.", translation: "Our group has been working on this project for three months.", answer: "Gruppe" },
  { sentence: "Die ______ aller Ergebnisse zeigt, dass das Projekt erfolgreich war.", translation: "The total of all the results shows that the project was successful.", answer: "Summe" },
  { sentence: "Jeder Mitarbeiter übernimmt einen ______ der Präsentation.", translation: "Each employee takes responsibility for a part of the presentation.", answer: "Teil" },
  { sentence: "Können Sie uns ein ______ aus Ihrem Arbeitsalltag nennen?", translation: "Can you give us an example from your everyday work?", answer: "Beispiel" },
  { sentence: "Nächste Woche findet eine ______ zur neuen Software statt.", translation: "Next week there will be training on the new software.", answer: "Schulung" },
  { sentence: "Unser ______ legt großen Wert auf gute Teamarbeit.", translation: "Our company places great importance on good teamwork.", answer: "Unternehmen" },
  { sentence: "Die erfolgreiche Präsentation war für das gesamte Team eine positive ______.", translation: "The successful presentation was a positive surprise for the whole team.", answer: "Überraschung" },
  { sentence: "Gemeinsam konnte das Team sehr gute Ergebnisse ______.", translation: "Together, the team was able to achieve very good results.", answer: "erzielen" },
  { sentence: "Das ______ der gemeinsamen Arbeit kann sich sehen lassen.", translation: "The result of the joint work is impressive.", answer: "Ergebnis" },
  { sentence: "Das Projekt war besonders ______, weil alle gut zusammengearbeitet haben.", translation: "The project was particularly successful because everyone worked well together.", answer: "erfolgreich" },
  { sentence: "Wir müssen die Aufgaben gerecht unter den Teammitgliedern ______.", translation: "We need to divide the tasks fairly among the team members.", answer: "aufteilen" },
  { sentence: "Für diese Position ist eine hohe fachliche ______ erforderlich.", translation: "A high level of professional competence is required for this position.", answer: "Kompetenz" },
  { sentence: "Einmal im Monat muss das gesamte Team zu einem gemeinsamen Gespräch ______.", translation: "Once a month, the entire team comes together for a meeting.", answer: "zusammenkommen" },
  { sentence: "Diese ______ kann nur gemeinsam gelöst werden.", translation: "This task can only be solved together.", answer: "Aufgabe" },
  { sentence: "Es war kein ______, dass beide Kollegen dieselbe Idee hatten.", translation: "It was not chance that both colleagues had the same idea.", answer: "Zufall" },
  { sentence: "Jedes ______ darf seine Meinung äußern.", translation: "Every team member is allowed to express their opinion.", answer: "Teammitglied" },
  { sentence: "Die Kollegen unterstützen sich ______, wenn es Probleme gibt.", translation: "The colleagues support each other when there are problems.", answer: "gegenseitig" },
  { sentence: "Die unterschiedlichen Erfahrungen der Mitarbeiter ______ sich gut.", translation: "The employees' different experiences complement each other well.", answer: "ergänzen" },
  { sentence: "______ finden Sie eine Übersicht über die wichtigsten Aufgaben.", translation: "The following is an overview of the most important tasks.", answer: "Folgend" },
  { sentence: "In unserem Team ist er der ______, der Ideen schnell in die Praxis umsetzt.", translation: "In our team, he is the doer who quickly puts ideas into practice.", answer: "Macher" },
  { sentence: "Bei neuen Arbeitsmethoden ist unser Chef eher ______.", translation: "When it comes to new working methods, our boss is rather conservative.", answer: "konservativ" },
  { sentence: "Viele Mitarbeiter ______ es, wenn sie selbstständig arbeiten können.", translation: "Many employees love being able to work independently.", answer: "lieben" },
  { sentence: "Eine gute Kommunikationssoftware ist ein wichtiges ______ für die Zusammenarbeit.", translation: "Good communication software is an important tool for collaboration.", answer: "Werkzeug" },
  { sentence: "Wir sollten zuerst eine neue Methode ______, bevor wir sie im ganzen Unternehmen einsetzen.", translation: "We should first try a new method before using it throughout the company.", answer: "probieren" },
  { sentence: "Für diese Aufgabe verwenden wir eine ______ Methode.", translation: "For this task, we use a time-tested method.", answer: "altbewährte" },
  { sentence: "Bevor wir die alten Ideen ______, sollten wir prüfen, ob wir sie noch brauchen.", translation: "Before we throw away the old ideas, we should check whether we still need them.", answer: "werfen" },
  { sentence: "Bei der Zusammenarbeit sollte jeder ______ auf die anderen nehmen.", translation: "When working together, everyone should show consideration for the others.", answer: "Rücksicht" },
  { sentence: "Der Ausfall eines wichtigen Mitarbeiters wäre ein großer ______ für das Team.", translation: "The absence of an important employee would be a major loss for the team.", answer: "Verlust" },
  { sentence: "Unterschiedliche Aufgaben sorgen für mehr ______ im Arbeitsalltag.", translation: "Different tasks provide more variety in everyday work.", answer: "Abwechslung" },
  { sentence: "Nach der Schulung haben alle Mitarbeiter neue Informationen ______.", translation: "After the training, all employees received new information.", answer: "erhalten" },
  { sentence: "In einem guten Team können Menschen mit ______ Erfahrungen voneinander lernen.", translation: "In a good team, people with different experiences can learn from each other.", answer: "unterschiedlichen" },
  { sentence: "Wir sollten großen Wert auf eine offene Kommunikation ______.", translation: "We should place great importance on open communication.", answer: "legen" },
  { sentence: "Ihre ______ könnte die Zusammenarbeit im Team verbessern.", translation: "Her idea could improve teamwork.", answer: "Idee" },
  { sentence: "Eine konkrete ______ ist oft wichtiger als eine lange Diskussion.", translation: "A concrete action is often more important than a long discussion.", answer: "Handlung" },
  { sentence: "______ möchten wir die Zusammenarbeit zwischen den Abteilungen verbessern.", translation: "In the long term, we want to improve cooperation between the departments.", answer: "Längerfristig" },
  { sentence: "Die Ergebnisse ______ darauf hin, dass wir den Plan ändern müssen.", translation: "The results indicate that we need to change the plan.", answer: "weisen" },
  { sentence: "Wir können die beiden Vorschläge ______, um eine bessere Lösung zu finden.", translation: "We can combine the two suggestions to find a better solution.", answer: "kombinieren" },
  { sentence: "Wenn wir den Plan zu schnell ändern, besteht ein ______.", translation: "If we change the plan too quickly, there is a risk.", answer: "Risiko" },
  { sentence: "Vor Beginn des Projekts müssen wir klare Ziele ______.", translation: "Before starting the project, we need to set clear goals.", answer: "festlegen" },
  { sentence: "Eine gemeinsame ______ kann den Zusammenhalt im Team stärken.", translation: "A joint activity can strengthen team cohesion.", answer: "Aktivität" },
  { sentence: "Für einige Mitarbeiter ist ein neues Projekt ein echtes ______.", translation: "For some employees, a new project is a real adventure.", answer: "Abenteuer" },
  { sentence: "Bei unserem Teamtag möchten wir gemeinsam Zeit in der ______ verbringen.", translation: "During our team day, we want to spend time together in nature.", answer: "Natur" },
  { sentence: "Während des Teamausflugs konnten wir viele neue Dinge ______.", translation: "During the team trip, we were able to experience many new things.", answer: "erleben" },
  { sentence: "Wir möchten verschiedene Arbeitsmethoden ______ und anschließend vergleichen.", translation: "We want to try out different working methods and then compare them.", answer: "ausprobieren" },
  { sentence: "Bei diesem Projekt konnten wir viele neue Erfahrungen ______.", translation: "During this project, we were able to collect many new experiences.", answer: "sammeln" },
  { sentence: "Während der Reise führte sie ein ______, in dem sie ihre Erfahrungen notierte.", translation: "During the trip, she kept a diary in which she wrote down her experiences.", answer: "Tagebuch" },
  { sentence: "Nach dem Teamtreffen soll jeder Mitarbeiter einen kurzen Bericht ______.", translation: "After the team meeting, every employee should write a short report.", answer: "schreiben" },
  { sentence: "Bei der gemeinsamen Aktivität konnten sich die neuen Kollegen besser ______.", translation: "During the joint activity, the new colleagues were able to get to know each other better.", answer: "kennenlernen" },
  { sentence: "In ihrer Freizeit arbeitet sie ehrenamtlich in einem ______.", translation: "In her free time, she volunteers at an association.", answer: "Verein" },
  { sentence: "Wir sollten offen miteinander ______, wenn es ein Problem gibt.", translation: "We should talk openly with each other when there is a problem.", answer: "reden" },
  { sentence: "Wenn etwas nicht nach Plan läuft, muss man manchmal ______.", translation: "When something does not go according to plan, sometimes you have to improvise.", answer: "improvisieren" },
  { sentence: "Das neue Büro ist ein angenehmer ______ für konzentriertes Arbeiten.", translation: "The new office is a pleasant place for focused work.", answer: "Ort" },
  { sentence: "Nach einem stressigen Projekt brauche ich dringend ______.", translation: "After a stressful project, I urgently need a vacation.", answer: "Urlaub" },
  { sentence: "Eine große ______ unseres Teams ist die gute Kommunikation.", translation: "A major strength of our team is good communication.", answer: "Stärke" },
  { sentence: "Bei der Arbeit im Homeoffice ist ______ besonders wichtig.", translation: "When working from home, flexibility is particularly important.", answer: "Flexibilität" },
  { sentence: "Seine ______ hilft dem Team, neue Lösungen zu finden.", translation: "His willingness to experiment helps the team find new solutions.", answer: "Experimentierfreude" },
  { sentence: "Für diese Stelle ist berufliche ______ erforderlich.", translation: "Professional mobility is required for this position.", answer: "Mobilität" },
  { sentence: "Bei der Arbeit mit Kundendaten muss ______ an erster Stelle stehen.", translation: "When working with customer data, security must come first.", answer: "Sicherheit" },
  { sentence: "Für ein langfristiges Projekt braucht man viel ______.", translation: "A long-term project requires a lot of perseverance.", answer: "Ausdauer" },
  { sentence: "Die ______ der Mitarbeiter zum Unternehmen ist bemerkenswert.", translation: "The employees' loyalty to the company is remarkable.", answer: "Treue" },
  { sentence: "Als ______ untersucht er die Daten sehr genau, bevor er eine Entscheidung trifft.", translation: "As an analyst, he examines the data carefully before making a decision.", answer: "Analytiker" },
  { sentence: "Der ______ im Team denkt schon an die Entwicklung des Unternehmens in zehn Jahren.", translation: "The visionary in the team is already thinking about the company's development in ten years.", answer: "Visionär" },
  { sentence: "Die neuen Mitarbeiter ______ eine eigene Lerngruppe.", translation: "The new employees form their own study group.", answer: "bilden" },
  { sentence: "Der kreative Kollege ist ein guter ______ zum sehr strukturierten Projektleiter.", translation: "The creative colleague is a good counterpart to the very structured project manager.", answer: "Gegenpol" },
  { sentence: "Die neue Software ist eine wichtige ______ für unser Unternehmen.", translation: "The new software is an important innovation for our company.", answer: "Neuerung" },
  { sentence: "Es ist wichtig, die Perspektive der anderen Teammitglieder zu ______.", translation: "It is important to understand the perspective of the other team members.", answer: "verstehen" },
  { sentence: "Bevor wir die neue Methode einsetzen, müssen wir sie zunächst ______.", translation: "Before using the new method, we first have to test it.", answer: "erproben" },
  { sentence: "Gute Ideen sind wichtig, aber erst die ______ führt zu konkreten Ergebnissen.", translation: "Good ideas are important, but only action leads to concrete results.", answer: "Tat" },
  { sentence: "Das Team möchte die neuen Ideen schnell ______.", translation: "The team wants to implement the new ideas quickly.", answer: "umsetzen" },
  { sentence: "Das neue System bietet uns die ______, flexibler zu arbeiten.", translation: "The new system gives us the possibility to work more flexibly.", answer: "Möglichkeit" },
  { sentence: "Wir müssen das Problem ______ analysieren.", translation: "We need to analyze the problem systematically.", answer: "systematisch" },
  { sentence: "Als ______ überprüft er jeden Bericht mehrmals.", translation: "As a perfectionist, he checks every report several times.", answer: "Perfektionist" },
  { sentence: "Für diese Aufgabe braucht man nicht nur Erfahrung, sondern auch gutes ______.", translation: "This task requires not only experience, but also good factual knowledge.", answer: "Faktenwissen" },
  { sentence: "Ein gutes Team sollte auch über den eigenen ______ hinausblicken.", translation: "A good team should also look beyond its own horizon.", answer: "Tellerrand" },
  { sentence: "Die aktuelle ______ zeigt, dass die Produktivität gestiegen ist.", translation: "The current statistics show that productivity has increased.", answer: "Statistik" },
  { sentence: "Unser ______ lautet: „Gemeinsam finden wir eine Lösung.“", translation: "Our motto is: “Together we will find a solution.”", answer: "Motto" },
  { sentence: "Gute Teamarbeit funktioniert nur, wenn die Kollegen einander ______.", translation: "Good teamwork only works when colleagues trust each other.", answer: "vertrauen" },
  { sentence: "Wir sollten über die aktuellen Probleme ______ und langfristig denken.", translation: "We should look beyond the current problems and think long-term.", answer: "hinausschauen" },
  { sentence: "Die Idee ist interessant, ______ ist sie ziemlich teuer.", translation: "The idea is interesting; however, it is quite expensive.", answer: "allerdings" },
  { sentence: "Bei zu vielen Änderungen kann das Team schnell den Überblick ______.", translation: "With too many changes, the team can quickly lose track.", answer: "verlieren" },
  { sentence: "Bei einem großen Projekt darf man nicht die ______ über die wichtigsten Aufgaben verlieren.", translation: "In a large project, you must not lose control of the most important tasks.", answer: "Kontrolle" },
  { sentence: "Die Planung muss mit der ______ übereinstimmen.", translation: "The planning must correspond to reality.", answer: "Realität" },
  { sentence: "Bei der Bewerbung müssen alle ______ eingehalten werden.", translation: "All formal requirements must be followed when applying.", answer: "formalen Vorgaben" },
  { sentence: "Bei Entscheidungen arbeitet sie ______ analytisch als intuitiv.", translation: "When making decisions, she works rather analytically than intuitively.", answer: "eher" },
  { sentence: "Als ______ entscheidet er meistens nach Fakten und nicht nach Gefühlen.", translation: "As a head-driven person, he usually makes decisions based on facts rather than feelings.", answer: "Kopfmensch" },
  { sentence: "Sie ist eher ein ______ und achtet stark auf die Stimmung im Team.", translation: "She is more of an emotional person and pays close attention to the mood in the team.", answer: "Gefühlsmensch" },
  { sentence: "Probleme im Team sollte man nicht einfach ______.", translation: "You should not simply ignore problems in a team.", answer: "ignorieren" },
  { sentence: "Die neue ______ erleichtert die Zusammenarbeit im Team.", translation: "The new software makes teamwork easier.", answer: "Software" },
  { sentence: "Er kann sehr gut ______ und entwickelt interne Tools für das Unternehmen.", translation: "He can program very well and develops internal tools for the company.", answer: "programmieren" },
  { sentence: "Durch ein ______ kann man wertvolle Erfahrungen sammeln.", translation: "Through voluntary work, you can gain valuable experience.", answer: "Ehrenamt" },
  { sentence: "Neben ihrem Beruf möchte sie ein Ehrenamt ______.", translation: "Besides her job, she does voluntary work.", answer: "ausüben" },
  { sentence: "Ohne einen klaren ______ ist es schwierig, ein Projekt erfolgreich umzusetzen.", translation: "Without a clear plan, it is difficult to implement a project successfully.", answer: "Plan" },
  { sentence: "Das Team möchte gemeinsam eine neue Strategie ______.", translation: "The team wants to develop a new strategy together.", answer: "entwickeln" },
  { sentence: "Bei unserer Arbeit müssen wir die geltenden ______ beachten.", translation: "In our work, we have to follow the applicable laws.", answer: "Gesetze" },
  { sentence: "Vor der Entscheidung sollte man die Ergebnisse genau ______.", translation: "Before making the decision, you should study the results carefully.", answer: "studieren" },
  { sentence: "Sie wird das neue Projekt ______.", translation: "She will lead the new project.", answer: "leiten" },
  { sentence: "Eine klare ______ hilft uns, den Überblick über die Aufgaben zu behalten.", translation: "A clear order or structure helps us keep track of the tasks.", answer: "Ordnung" },
  { sentence: "Im Team können Mitarbeiter ihr ______ miteinander teilen.", translation: "In a team, employees can share their knowledge with each other.", answer: "Wissen" },
  { sentence: "Bei der Verteilung der Aufgaben sollte ______ eine wichtige Rolle spielen.", translation: "When distributing tasks, fairness should play an important role.", answer: "Gerechtigkeit" },
  { sentence: "Seine ______ bringt ihn dazu, ständig neue Dinge zu lernen.", translation: "His curiosity motivates him to constantly learn new things.", answer: "Neugier" },
  { sentence: "Für langfristiges Wachstum braucht ein Unternehmen ______.", translation: "A company needs innovation for long-term growth.", answer: "Innovation" },
  { sentence: "Das Unternehmen plant für das nächste Jahr ein starkes ______.", translation: "The company is planning strong growth for next year.", answer: "Wachstum" },
  { sentence: "Bevor wir anfangen, sollten wir die Informationen ______.", translation: "Before we start, we should organize the information.", answer: "ordnen" },
  { sentence: "Ohne klare Zuständigkeiten kann die Zusammenarbeit schnell ______ werden.", translation: "Without clear responsibilities, collaboration can quickly become chaotic.", answer: "chaotisch" },
  { sentence: "Es wäre ______, zuerst die wichtigsten Aufgaben zu erledigen.", translation: "It would be sensible to complete the most important tasks first.", answer: "vernünftig" },
  { sentence: "Wir sollten keine ______ Entscheidung treffen.", translation: "We should not make a hasty decision.", answer: "voreilige" },
  { sentence: "Die neue Lösung ist einfach und ______.", translation: "The new solution is simple and practical.", answer: "praktisch" },
  { sentence: "Die neuen Mitarbeiter haben ______ auf die Projektidee reagiert.", translation: "The new employees reacted enthusiastically to the project idea.", answer: "enthusiastisch" },
  { sentence: "Seine ______ Äußerung hat zu einer langen Diskussion geführt.", translation: "His provocative remark led to a long discussion.", answer: "provozierende" },
  { sentence: "Man sollte nicht zu ______ sein, bevor wir die Ergebnisse kennen.", translation: "We should not be too pessimistic before we know the results.", answer: "pessimistisch" },
  { sentence: "Trotz der Schwierigkeiten bleibt die Teamleiterin ______.", translation: "Despite the difficulties, the team leader remains optimistic.", answer: "optimistisch" },
  { sentence: "Es ist wichtig, dass alle Mitarbeiter ______ zum Teamgespräch kommen.", translation: "It is important that all employees arrive on time for the team meeting.", answer: "pünktlich" },
  { sentence: "Meine ______ hat mir schon als Kind gezeigt, wie wichtig Zusammenarbeit ist.", translation: "My favorite aunt taught me even as a child how important cooperation is.", answer: "Lieblingstante" },
  { sentence: "Der Verein organisiert regelmäßig Aktivitäten für Menschen im ______.", translation: "The association regularly organizes activities for people in a nursing home.", answer: "Altersheim" },
  { sentence: "Wir müssen den neuen Arbeitsplatz noch ______.", translation: "We still need to set up the new workplace.", answer: "einrichten" },
  { sentence: "Für die neuen Mitarbeiter organisieren wir eine kleine ______.", translation: "We are organizing a small welcome party for the new employees.", answer: "Willkommensparty" },
  { sentence: "Die Organisation unterstützt Menschen, die kein eigenes ______ haben.", translation: "The organization supports people who do not have their own home.", answer: "Heim" },
  { sentence: "Der Geschäftsführer hielt eine kurze ______ zum Jubiläum des Unternehmens.", translation: "The managing director gave a short speech for the company's anniversary.", answer: "Rede" },
  { sentence: "Die Projektleiterin wird morgen eine Präsentation ______.", translation: "The project manager will give a presentation tomorrow.", answer: "halten" },
  { sentence: "In einem internationalen Team kann man unterschiedliche Kulturen ______.", translation: "In an international team, you can experience different cultures.", answer: "leben" },
  { sentence: "Unser ______ unterstützt neue Ideen und gibt den Mitarbeitern viel Freiheit.", translation: "Our boss supports new ideas and gives employees a lot of freedom.", answer: "Chef" },
  { sentence: "Wie sollte man ______, wenn ein Teammitglied einen Fehler macht?", translation: "How should one react when a team member makes a mistake?", answer: "reagieren" },
  { sentence: "Als Teamevent haben wir eine ______ auf der Donau geplant.", translation: "As a team event, we planned a river trip on the Danube.", answer: "Flussreise" },
  { sentence: "Während des Ausflugs konnten wir mit einem ______ auf dem Fluss fahren.", translation: "During the trip, we could travel along the river in a paddle boat.", answer: "Paddelboot" },
  { sentence: "Bei der gemeinsamen Reise konnten wir einen neuen Ort ______.", translation: "During the trip together, we were able to discover a new place.", answer: "entdecken" },
  { sentence: "Seine ______ wurde von einigen Kollegen als unhöflich empfunden.", translation: "Some colleagues considered his remark rude.", answer: "Äußerung" },
  { sentence: "Gemeinsam können wir unser Ziel schneller ______.", translation: "Together, we can reach our goal faster.", answer: "erreichen" },
  { sentence: "Wir sollten dieses Problem morgen im Team ______.", translation: "We should discuss this problem in the team tomorrow.", answer: "besprechen" },
  { sentence: "Nach der Veranstaltung gingen alle gemeinsam in ein ______.", translation: "After the event, everyone went to a restaurant together.", answer: "Restaurant" },
  { sentence: "Nach dem Unfall musste der Mitarbeiter ins ______ gebracht werden.", translation: "After the accident, the employee had to be taken to the hospital.", answer: "Krankenhaus" },
  { sentence: "Die Mitarbeiter des Unternehmens sammeln jedes Jahr Spenden für ein ______.", translation: "The company's employees collect donations for a children's home every year.", answer: "Kinderheim" },
  { sentence: "Wir haben für unser Team ein abwechslungsreiches ______ organisiert.", translation: "We organized a varied weekend program for our team.", answer: "Wochenendprogramm" },
  { sentence: "Unsere ______ trifft sich jeden Freitag, um gemeinsam Deutsch zu lernen.", translation: "Our study group meets every Friday to learn German together.", answer: "Lerngruppe" },
  { sentence: "Vor der ______ lernen wir gemeinsam die wichtigsten Begriffe.", translation: "Before the exam, we study the most important terms together.", answer: "Prüfung" },
  { sentence: "Der ______ unserer Geschäftspartner beginnt um zehn Uhr.", translation: "The visit of our business partners begins at ten o'clock.", answer: "Besuch" },
  { sentence: "Die Teamleiterin wird die Besprechung mit einer kurzen Einleitung ______.", translation: "The team leader will open the meeting with a short introduction.", answer: "eröffnen" },
  { sentence: "Wir müssen uns gut auf das nächste Teamgespräch ______.", translation: "We need to prepare well for the next team meeting.", answer: "vorbereiten" },
];

const sourceWords = getTeamrolleSet().words;

export const TEAMROLLE_GAP_TEST: GapTestQuestion[] = PROMPTS.flatMap((prompt, index) => {
  const word = sourceWords[index];
  return word ? [{ ...prompt, wordId: word.id }] : [];
});

export const TEAMROLLE_GAP_WORD_IDS = new Set(
  TEAMROLLE_GAP_TEST.map((prompt) => prompt.wordId),
);