import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["das Teamgespräch", "team talk / meeting", "noun"],
  ["führen", "to lead / conduct", "verb"],
  ["ungünstig", "unfavorable", "adjective"],
  ["lösen", "to solve / dissolve", "verb"],
  ["wunderbar", "wonderful", "adjective"],
  ["die Meinung", "opinion", "noun"],
  ["der Lieferant", "supplier", "noun"],
  ["der Punkt", "point", "noun"],
  ["die Idee", "idea", "noun"],
  ["richtig", "correct", "adjective"],
  ["verstehen", "to understand", "verb"],
  ["das Redemittel", "phrase / expression", "noun"],
  ["folgend", "following", "adjective"],
  ["sammeln", "to collect", "verb"],
  ["das Wort", "word", "noun"],
  ["melden", "to report / register", "verb"],
  ["meiden", "to avoid", "verb"],
  ["nachfragen", "to inquire / follow up", "verb"],
  ["vorschlagen", "to propose", "verb"],
  ["zustimmen", "to agree", "verb"],
  ["ablehnen", "to reject", "verb"],
  ["äußern", "to express / comment", "verb"],
  ["der Alternativvorschlag", "alternative proposal", "noun"],
  ["einige", "some", "pronoun"],
  ["wählen", "to choose / select", "verb"],
  ["die Situation", "situation", "noun"],
  ["die Notiz", "note", "noun"],
  ["das Kurzprotokoll", "short minutes / summary", "noun"],
  ["das Mitglied", "member", "noun"],
  ["der Tischtennisverein", "table tennis club", "noun"],
  ["die Ware", "product / goods", "noun"],
  ["die Vereinsmeisterschaft", "club championship", "noun"],
  ["organisieren", "to organize", "verb"],
  ["klein", "small", "adjective"],
  ["der Imbiss", "snack / snack bar", "noun"],
  ["der Familienbetrieb", "family business", "noun"],
  ["besprechen", "to discuss", "verb"],
  ["bitten", "to ask / request", "verb"],
  ["das Straßenfest", "street festival", "noun"],
  ["die Straße", "street / road", "noun"],
  ["überlegen", "to consider / think over", "verb"],
  ["zeitlich", "temporal / in time", "adjective"],
  ["der Ablauf", "procedure / sequence", "noun"],
  ["bieten", "to offer", "verb"],
  ["der Spielplan", "schedule / fixture list", "noun"],
  ["die Vorbereitung", "preparation", "noun"],
  ["der Gewinn", "profit / win", "noun"],
  ["die Siegerehrung", "award ceremony", "noun"],
  ["zusätzlich", "additional", "adjective"],
  ["die Party", "party", "noun"],
  ["das Getränk", "beverage", "noun"],
  ["schreiben", "to write", "verb"],
  ["gemeinsam", "joint / together", "other"],
  ["das Protokoll", "protocol / minutes", "noun"],
  ["die Erfahrung", "experience", "noun"],
  ["die Aufgabe", "task", "noun"],
  ["gefallen", "to please / like", "verb"],
  ["das Jahr", "year", "noun"],
  ["der Pflegedienst", "care service", "noun"],
  ["meistens", "mostly", "adverb"],
  ["die Stärke", "strength", "noun"],
  ["vermitteln", "to convey / mediate", "verb"],
  ["der Konflikt", "conflict", "noun"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const TEAMGESPRÄCH_SET_ID = "b31e6dd3-0faf-4993-ae61-0b9eb970f4c1";
export const TEAMGESPRÄCH_SET_NAME = "Kapitel 3 - Teamgespräch";

export function getTeamgesprächSet(): StudySet {
  return {
    id: TEAMGESPRÄCH_SET_ID,
    name: TEAMGESPRÄCH_SET_NAME,
    createdAt: 0,
    sourceImageCount: 1,
    words: RAW_WORDS.map((word, index) => ({ id: `${TEAMGESPRÄCH_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
