import { StudySet, VocabWord } from "./types";

const RAW_WORDS: Omit<VocabWord, "id">[] = [
  ["der Umzug", "the move / relocation", "noun"],
  ["die Umzugsfirma", "the moving company", "noun"],
  ["der Umzugstag", "the moving day", "noun"],
  ["das Angebot", "the offer / quote", "noun"],
  ["die Nachfrage", "the inquiry / demand", "noun"],
  ["das Detail", "the detail", "noun"],
  ["der Kunde", "the customer (male)", "noun"],
  ["die Kundin", "the customer (female)", "noun"],
  ["die Spülmaschine", "the dishwasher", "noun"],
  ["der Kaffeeautomat", "the coffee machine", "noun"],
  ["das Regal", "the shelf", "noun"],
  ["der Mitarbeiter", "the employee (male)", "noun"],
  ["die Mitarbeiterin", "the employee (female)", "noun"],
  ["das Büro", "the office", "noun"],
  ["das Stockwerk", "the floor / storey", "noun"],
  ["der Termin", "the appointment / date", "noun"],
  ["der Schreibtisch", "the desk", "noun"],
  ["das Möbel", "the piece of furniture", "noun"],
  ["der Karton", "the box / carton", "noun"],
  ["der Fixpreis", "the fixed price", "noun"],
  ["der Samstagvormittag", "the Saturday morning", "noun"],
  ["der Hof", "the courtyard", "noun"],
  ["die Einbauküche", "the fitted kitchen", "noun"],
  ["der Stock", "the floor / storey", "noun"],
  ["die Parkmöglichkeit", "the parking option", "noun"],
  ["der Anfang", "the beginning", "noun"],
  ["der Dezember", "December", "noun"],
  ["der Besichtigungstermin", "the viewing appointment", "noun"],
  ["die Besichtigung", "the inspection / viewing", "noun"],
  ["die Woche", "the week", "noun"],
  ["der Aufzug", "the elevator / lift", "noun"],
  ["die Situation", "the situation", "noun"],
  ["die Notiz", "the note", "noun"],
  ["der Imbiss", "the snack bar / eatery", "noun"],
  ["der Name", "the name", "noun"],
  ["der Tag", "the day", "noun"],
  ["einholen", "to obtain / get", "verb"],
  ["klären", "to clarify", "verb"],
  ["verhandeln", "to negotiate", "verb"],
  ["schicken", "to send", "verb"],
  ["umziehen", "to move (house/office)", "verb"],
  ["mitnehmen", "to take along", "verb"],
  ["entsorgen", "to dispose of", "verb"],
  ["können", "to be able to / can", "verb"],
  ["wollen", "to want", "verb"],
  ["müssen", "to have to / must", "verb"],
  ["parken", "to park", "verb"],
  ["möchten", "would like", "verb"],
  ["abbauen", "to dismantle", "verb"],
  ["sollen", "should / ought to", "verb"],
  ["erledigen", "to handle / complete", "verb"],
  ["packen", "to pack", "verb"],
  ["ausbuchen", "to fully book / be booked out", "verb"],
  ["entgegenkommen", "to meet halfway / accommodate", "verb"],
  ["machen", "to do / make", "verb"],
  ["haben", "to have", "verb"],
  ["beauftragen", "to commission / hire", "verb"],
  ["anbieten", "to offer", "verb"],
  ["bleiben", "to stay / remain", "verb"],
  ["mitkommen", "to come along", "verb"],
  ["aufbauen", "to assemble / set up", "verb"],
  ["tun", "to do", "verb"],
  ["sein", "to be", "verb"],
  ["gehen", "to go / work out", "verb"],
  ["austauschen", "to exchange / discuss", "verb"],
  ["arbeiten", "to work", "verb"],
  ["genau", "exactly / precise", "other"],
  ["neu", "new", "adjective"],
  ["alt", "old", "adjective"],
  ["groß", "big / large", "adjective"],
  ["jetzig", "current", "adjective"],
  ["selbst", "self / personally", "adverb"],
  ["leider", "unfortunately", "adverb"],
  ["früh", "early", "adjective"],
  ["möglich", "possible", "adjective"],
  ["nächst", "next", "adjective"],
  ["übrig", "remaining / other", "adjective"],
  ["gut", "good", "adjective"],
  ["dann", "then", "adverb"],
  ["mal", "sometimes / once", "adverb"],
  ["bitte", "please", "adverb"],
].map(([german, english, pos]) => ({ german, english, pos, example: "" }));

export const UMZUG_SET_ID = "aed92006-9161-46d9-b09b-7258a00942fe";
export const UMZUG_SET_NAME = "Kapitel 1 - Umzug";

export function getUmzugSet(): StudySet {
  return {
    id: UMZUG_SET_ID,
    name: UMZUG_SET_NAME,
    createdAt: 0,
    sourceImageCount: 1,
    words: RAW_WORDS.map((word, index) => ({ id: `${UMZUG_SET_ID}-${index}`, ...word })),
    masteredWordIds: [],
  };
}
