import { VocabWord } from "./types";

// Vocabulary matching the "Workspaces, Moving and Renting Premises" Figma set.
const RAW_WORDS: Omit<VocabWord, "id">[] = [
  {
    german: "der Arbeitsraum",
    english: "workspace",
    pos: "noun",
    example: "Unser Arbeitsraum ist hell und ruhig.",
  },
  {
    german: "das Büro",
    english: "office",
    pos: "noun",
    example: "Das Büro liegt im zweiten Stock.",
  },
  {
    german: "die Werkstatt",
    english: "workshop",
    pos: "noun",
    example: "In der Werkstatt steht eine große Werkbank.",
  },
  {
    german: "der Gewerberaum",
    english: "commercial premises",
    pos: "noun",
    example: "Dieser Gewerberaum eignet sich für ein Café.",
  },
  {
    german: "die Kaffeemaschine",
    english: "coffee machine",
    pos: "noun",
    example: "Die Kaffeemaschine steht in der Küche.",
  },
  {
    german: "der Hocker",
    english: "stool",
    pos: "noun",
    example: "Neben dem Tisch steht ein Hocker.",
  },
  {
    german: "die Leiter",
    english: "ladder",
    pos: "noun",
    example: "Zum Streichen brauche ich eine Leiter.",
  },
  {
    german: "die Arbeitsschürze",
    english: "work apron",
    pos: "noun",
    example: "Meine Arbeitsschürze schützt die Kleidung.",
  },
  {
    german: "die Werkbank",
    english: "workbench",
    pos: "noun",
    example: "Das Werkzeug liegt auf der Werkbank.",
  },
  {
    german: "der Helm",
    english: "helmet",
    pos: "noun",
    example: "Auf der Baustelle ist ein Helm Pflicht.",
  },
  {
    german: "der Werkzeugkasten",
    english: "toolbox",
    pos: "noun",
    example: "Der Werkzeugkasten steht unter dem Tisch.",
  },
  {
    german: "die Klimaanlage",
    english: "air conditioning",
    pos: "noun",
    example: "Die Klimaanlage kühlt unser Büro.",
  },
  {
    german: "der Bildschirm",
    english: "screen",
    pos: "noun",
    example: "Mein Bildschirm ist zu klein.",
  },
  {
    german: "der Arbeitstisch",
    english: "work table",
    pos: "noun",
    example: "Der Arbeitstisch steht am Fenster.",
  },
  {
    german: "der Vermieter",
    english: "landlord",
    pos: "noun",
    example: "Unser Vermieter repariert die Heizung.",
  },
  {
    german: "die Miete",
    english: "rent",
    pos: "noun",
    example: "Die Miete ist hier sehr hoch.",
  },
  {
    german: "die Mieterhöhung",
    english: "rent increase",
    pos: "noun",
    example: "Wir haben eine Mieterhöhung bekommen.",
  },
  {
    german: "der Mietvertrag",
    english: "rental agreement",
    pos: "noun",
    example: "Bitte lesen Sie den Mietvertrag genau.",
  },
  {
    german: "die Kaution",
    english: "security deposit",
    pos: "noun",
    example: "Wir müssen eine Kaution hinterlegen.",
  },
  {
    german: "der Einkommensnachweis",
    english: "proof of income",
    pos: "noun",
    example: "Für die Bewerbung brauche ich einen Einkommensnachweis.",
  },
  {
    german: "der Grundriss",
    english: "floor plan",
    pos: "noun",
    example: "Der Grundriss zeigt alle Räume.",
  },
  {
    german: "die Lage",
    english: "location",
    pos: "noun",
    example: "Die Lage des Büros ist ideal.",
  },
  {
    german: "das Erdgeschoss",
    english: "ground floor",
    pos: "noun",
    example: "Unsere Werkstatt liegt im Erdgeschoss.",
  },
  {
    german: "der Aufzug",
    english: "elevator",
    pos: "noun",
    example: "Leider ist der Aufzug kaputt.",
  },
  {
    german: "die Hausverwaltung",
    english: "property management",
    pos: "noun",
    example: "Die Hausverwaltung kümmert sich um die Reparatur.",
  },
  {
    german: "die Unterlagen",
    english: "documents",
    pos: "noun",
    example: "Bitte bringen Sie alle Unterlagen mit.",
  },
  {
    german: "die Zusage",
    english: "acceptance; confirmation",
    pos: "noun",
    example: "Heute kam die Zusage für das Büro.",
  },
  {
    german: "der Umzug",
    english: "move; relocation",
    pos: "noun",
    example: "Unser Umzug findet am Samstag statt.",
  },
  {
    german: "der Umzugskarton",
    english: "moving box",
    pos: "noun",
    example: "Dieser Umzugskarton ist voller Bücher.",
  },
  {
    german: "der Nachsendeantrag",
    english: "mail forwarding request",
    pos: "noun",
    example: "Vor dem Umzug stellen wir einen Nachsendeantrag.",
  },
  {
    german: "die Spedition",
    english: "removal company; freight company",
    pos: "noun",
    example: "Die Spedition transportiert unsere Möbel.",
  },
  {
    german: "die Einweihungsparty",
    english: "housewarming party",
    pos: "noun",
    example: "Am Freitag feiern wir eine Einweihungsparty.",
  },
  {
    german: "der Handwerker",
    english: "tradesperson",
    pos: "noun",
    example: "Der Handwerker repariert die Tür.",
  },
  {
    german: "der Elektriker",
    english: "electrician",
    pos: "noun",
    example: "Der Elektriker prüft die Leitungen.",
  },
  {
    german: "der Fliesenleger",
    english: "tiler",
    pos: "noun",
    example: "Der Fliesenleger arbeitet im Badezimmer.",
  },
  {
    german: "der Installateur",
    english: "plumber; installer",
    pos: "noun",
    example: "Der Installateur repariert das Waschbecken.",
  },
  {
    german: "die Leitung",
    english: "wire; pipe; line",
    pos: "noun",
    example: "Der Elektriker legt eine neue Leitung.",
  },
  {
    german: "der Internetanschluss",
    english: "internet connection",
    pos: "noun",
    example: "Unser Internetanschluss funktioniert wieder.",
  },
  {
    german: "die Genehmigung",
    english: "permit; approval",
    pos: "noun",
    example: "Für das Café brauchen wir eine Genehmigung.",
  },
  {
    german: "die Vorschrift",
    english: "regulation",
    pos: "noun",
    example: "Diese Vorschrift gilt für alle Betriebe.",
  },
  {
    german: "das Übergabeprotokoll",
    english: "handover report",
    pos: "noun",
    example: "Wir unterschreiben das Übergabeprotokoll gemeinsam.",
  },
  {
    german: "der Mangel",
    english: "defect",
    pos: "noun",
    example: "Dieser Mangel muss repariert werden.",
  },
  {
    german: "die Lärmbelästigung",
    english: "noise nuisance",
    pos: "noun",
    example: "Die Lärmbelästigung stört uns bei der Arbeit.",
  },
  {
    german: "besichtigen",
    english: "to view; to inspect",
    pos: "verb",
    example: "Morgen möchten wir die Räume besichtigen.",
  },
  {
    german: "mieten",
    english: "to rent",
    pos: "verb",
    example: "Wir wollen ein größeres Büro mieten.",
  },
  {
    german: "unterschreiben",
    english: "to sign",
    pos: "verb",
    example: "Sie können den Vertrag heute unterschreiben.",
  },
  {
    german: "kündigen",
    english: "to terminate; to give notice",
    pos: "verb",
    example: "Wir müssen den alten Mietvertrag kündigen.",
  },
  {
    german: "umziehen",
    english: "to move",
    pos: "verb",
    example: "Unsere Firma möchte im Oktober umziehen.",
  },
  {
    german: "einziehen",
    english: "to move in",
    pos: "verb",
    example: "Ab Montag können wir einziehen.",
  },
  {
    german: "sich ummelden",
    english: "to register a change of address",
    pos: "verb",
    example: "Nach dem Umzug muss man sich ummelden.",
  },
  {
    german: "beauftragen",
    english: "to commission; to hire",
    pos: "verb",
    example: "Wir möchten eine Umzugsfirma beauftragen.",
  },
  {
    german: "renovieren",
    english: "to renovate",
    pos: "verb",
    example: "Wir müssen das Büro renovieren.",
  },
  {
    german: "sanieren",
    english: "to refurbish; to restore",
    pos: "verb",
    example: "Die Firma soll das alte Gebäude sanieren.",
  },
  {
    german: "abschleifen",
    english: "to sand down",
    pos: "verb",
    example: "Wir lassen die Böden abschleifen.",
  },
  {
    german: "streichen",
    english: "to paint",
    pos: "verb",
    example: "Ich möchte die Wände weiß streichen.",
  },
  {
    german: "anschließen",
    english: "to connect",
    pos: "verb",
    example: "Kannst du den Computer anschließen?",
  },
  {
    german: "einräumen",
    english: "to put away; to fill",
    pos: "verb",
    example: "Morgen können wir die Schränke einräumen.",
  },
  {
    german: "untervermieten",
    english: "to sublet",
    pos: "verb",
    example: "Dürfen wir einen Raum untervermieten?",
  },
  {
    german: "gründen",
    english: "to found; to set up",
    pos: "verb",
    example: "Wir wollen eine eigene Firma gründen.",
  },
  {
    german: "gebraucht",
    english: "second-hand; used",
    pos: "adjective",
    example: "Wir kaufen die Büromöbel gebraucht.",
  },
];

export const EXERCISE_SET_ID = "demo-workspaces-moving-renting";
export const EXERCISE_SET_NAME = "Workspaces, Moving and Renting Premises";

export function getExerciseSetWords(): VocabWord[] {
  return RAW_WORDS.map((w, i) => ({ id: `${EXERCISE_SET_ID}-${i}`, ...w }));
}
